version: '3.8'

services:
  frontend:
    build:
      context: ./react
      dockerfile: ./Dockerfile
    container_name: "react-js"
    ports:
      - "3000:3000"
  backend:
    build:
      context: ./spring
      dockerfile: ./Dockerfile
    container_name: "spring-java"
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: "on-failure"
  db:
    image: mysql:8.0.23
    container_name: "mysql"
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: team11
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root

