INSERT INTO product (productid,name ,type,  size ,color,finish,grade) VALUES('prod-1','Raaw bikes','Mountain','Medium','White','Matte','10%');
INSERT INTO product (productid,name ,type,  size ,color,finish,grade) VALUES('prod-2','Rocky bikes','Mountain','Large','Red','Polish','10%');
INSERT INTO product (productid,name ,type,  size ,color,finish,grade) VALUES('prod-3','Ghost bikes','Road','Small','Maroon','Polish','10%');
INSERT INTO product (productid,name ,type,  size ,color,finish,grade) VALUES('prod-4','Aero','Road','Large','Black','Matte','10%');
INSERT INTO product_inventory (id, location,quantity,productID) VALUES('prodinv-1','Warehouse', 5, 'prod-1');
INSERT INTO product_inventory (id, location,quantity,productID) VALUES('prodinv-2','Warehouse', 4, 'prod-2');
INSERT INTO product_inventory (id, location,quantity,productID) VALUES('prodinv-3','Warehouse', 8, 'prod-3');
INSERT INTO product_inventory (id, location,quantity,productID) VALUES('prodinv-4','Warehouse', 10, 'prod-4');
INSERT INTO part_inventory (id, location,quantity,partid) VALUES('prtinv-1','Warehouse', 20, 'prt-1');
INSERT INTO part_inventory (id, location,quantity,partid) VALUES('prtinv-2','Warehouse', 25, 'prt-2');
INSERT INTO part_inventory (id, location,quantity,partid) VALUES('prtinv-3','Warehouse', 30, 'prt-3');
INSERT INTO part_inventory (id, location,quantity,partid) VALUES('prtinv-4','Warehouse', 15, 'prt-4');
INSERT INTO part_inventory (id, location,quantity,partid) VALUES('prtinv-5','Warehouse', 18, 'prt-5');
INSERT INTO material_inventory (id, location,quantity,materialid) VALUES('matinv-1','Warehouse', 54, 'mat-1');
INSERT INTO material_inventory (id, location,quantity,materialid) VALUES('matinv-2','Warehouse', 84, 'mat-2');
INSERT INTO material_inventory (id, location,quantity,materialid) VALUES('matinv-3','Warehouse', 79, 'mat-3');
INSERT INTO material_inventory (id, location,quantity,materialid) VALUES('matinv-4','Warehouse', 64, 'mat-4');
INSERT INTO material_inventory (id, location,quantity,materialid) VALUES('matinv-5','Warehouse', 67, 'mat-5');
INSERT INTO material_inventory (id, location,quantity,materialid) VALUES('matinv-6','Warehouse', 58, 'mat-6');
INSERT INTO material_inventory (id, location,quantity,materialid) VALUES('matinv-7','Warehouse', 72, 'mat-7');
INSERT INTO material_inventory (id, location,quantity,materialid) VALUES('matinv-8','Warehouse', 75, 'mat-8');
INSERT INTO material_inventory (id, location,quantity,materialid) VALUES('matinv-9','Warehouse', 86, 'mat-9');
INSERT INTO material_inventory (id, location,quantity,materialid) VALUES('matinv-10','Warehouse', 68, 'mat-10');
INSERT INTO material_inventory (id, location,quantity,materialid) VALUES('matinv-11','Warehouse', 78, 'mat-11');
INSERT INTO material_inventory (id, location,quantity,materialid) VALUES('matinv-12','Warehouse', 69, 'mat-12');
INSERT INTO material_inventory (id, location,quantity,materialid) VALUES('matinv-13','Warehouse', 65, 'mat-13');
INSERT INTO material_inventory (id, location,quantity,materialid) VALUES('matinv-14','Warehouse', 20, 'mat-14');
INSERT INTO material_inventory (id, location,quantity,materialid) VALUES('matinv-15','Warehouse', 25, 'mat-15');
INSERT INTO material_inventory (id, location,quantity,materialid) VALUES('matinv-16','Warehouse', 65, 'mat-16');
INSERT INTO material_inventory (id, location,quantity,materialid) VALUES('matinv-17','Warehouse', 60, 'mat-17');
INSERT INTO material_inventory (id, location,quantity,materialid) VALUES('matinv-18','Warehouse', 55, 'mat-18');
INSERT INTO material_inventory (id, location,quantity,materialid) VALUES('matinv-19','Warehouse', 60, 'mat-19');
INSERT INTO material_inventory (id, location,quantity,materialid) VALUES('matinv-20','Warehouse', 30, 'mat-20');
INSERT INTO material_inventory (id, location,quantity,materialid) VALUES('matinv-21','Warehouse', 35, 'mat-21');
INSERT INTO material_inventory (id, location,quantity,materialid) VALUES('matinv-22','Warehouse', 600, 'mat-22');
INSERT INTO material_inventory (id, location,quantity,materialid) VALUES('matinv-23','Warehouse', 50, 'mat-23');
INSERT INTO material_inventory (id, location,quantity,materialid) VALUES('matinv-24','Warehouse', 69, 'mat-24');



