-- This is instances for part table
INSERT INTO part (partid, name) VALUES ('sd-m1snp', 'Saddle / Mountain / Small / Black / Polish / 9%');
INSERT INTO part (partid, name) VALUES ('fr-m1snp', 'Frame / Mountain / Small / Black / Polish / 9%');
INSERT INTO part (partid, name) VALUES ('wh-m1snp', 'Wheels / Mountain / Small / Black / Polish / 9%');
INSERT INTO part (partid, name) VALUES ('fs-m1snp', 'Front Set / Mountain / Small / Black / Polish / 9%');
INSERT INTO part (partid, name) VALUES ('pu-m1snp', 'Pedal Unit / Mountain / Small / Black / Polish / 9%');
INSERT INTO part (partid, name) VALUES ('sd-m1snm', 'Saddle / Mountain / Small / Black / Matte / 9%');
INSERT INTO part (partid, name) VALUES ('fr-m1snm', 'Frame / Mountain / Small / Black / Matte / 9%');
INSERT INTO part (partid, name) VALUES ('wh-m1snm', 'Wheels / Mountain / Small / Black / Matte / 9%');
INSERT INTO part (partid, name) VALUES ('fs-m1snm', 'Front Set / Mountain / Small / Black / Matte / 9%');
INSERT INTO part (partid, name) VALUES ('pu-m1snm', 'Pedal Unit / Mountain / Small / Black / Matte / 9%');
INSERT INTO part (partid, name) VALUES ('sd-m1swp', 'Saddle / Mountain / Small / White / Polish / 9%');
INSERT INTO part (partid, name) VALUES ('fr-m1swp', 'Frame / Mountain / Small / White / Polish / 9%');
INSERT INTO part (partid, name) VALUES ('wh-m1swp', 'Wheels / Mountain / Small / White / Polish / 9%');
INSERT INTO part (partid, name) VALUES ('fs-m1swp', 'Front Set / Mountain / Small / White / Polish / 9%');
INSERT INTO part (partid, name) VALUES ('pu-m1swp', 'Pedal Unit / Mountain / Small / White / Polish / 9%');
INSERT INTO part (partid, name) VALUES ('sd-m1swm', 'Saddle / Mountain / Small / White / Matte / 9%');
INSERT INTO part (partid, name) VALUES ('fr-m1swm', 'Frame / Mountain / Small / White / Matte / 9%');
INSERT INTO part (partid, name) VALUES ('wh-m1swm', 'Wheels / Mountain / Small / White / Matte / 9%');
INSERT INTO part (partid, name) VALUES ('fs-m1swm', 'Front Set / Mountain / Small / White / Matte / 9%');
INSERT INTO part (partid, name) VALUES ('pu-m1swm', 'Pedal Unit / Mountain / Small / White / Matte / 9%');
INSERT INTO part (partid, name) VALUES ('sd-m1sbp', 'Saddle / Mountain / Small / Blue / Polish / 9%');
INSERT INTO part (partid, name) VALUES ('fr-m1sbp', 'Frame / Mountain / Small / Blue / Polish / 9%');
INSERT INTO part (partid, name) VALUES ('wh-m1sbp', 'Wheels / Mountain / Small / Blue / Polish / 9%');
INSERT INTO part (partid, name) VALUES ('fs-m1sbp', 'Front Set / Mountain / Small / Blue / Polish / 9%');
INSERT INTO part (partid, name) VALUES ('pu-m1sbp', 'Pedal Unit / Mountain / Small / Blue / Polish / 9%');
INSERT INTO part (partid, name) VALUES ('sd-m1sbm', 'Saddle / Mountain / Small / Blue / Matte / 9%');
INSERT INTO part (partid, name) VALUES ('fr-m1sbm', 'Frame / Mountain / Small / Blue / Matte / 9%');
INSERT INTO part (partid, name) VALUES ('wh-m1sbm', 'Wheels / Mountain / Small / Blue / Matte / 9%');
INSERT INTO part (partid, name) VALUES ('fs-m1sbm', 'Front Set / Mountain / Small / Blue / Matte / 9%');
INSERT INTO part (partid, name) VALUES ('pu-m1sbm', 'Pedal Unit / Mountain / Small / Blue / Matte / 9%');
INSERT INTO part (partid, name) VALUES ('sd-m1syp', 'Saddle / Mountain / Small / Yellow / Polish / 9%');
INSERT INTO part (partid, name) VALUES ('fr-m1syp', 'Frame / Mountain / Small / Yellow / Polish / 9%');
INSERT INTO part (partid, name) VALUES ('wh-m1syp', 'Wheels / Mountain / Small / Yellow / Polish / 9%');
INSERT INTO part (partid, name) VALUES ('fs-m1syp', 'Front Set / Mountain / Small / Yellow / Polish / 9%');
INSERT INTO part (partid, name) VALUES ('pu-m1syp', 'Pedal Unit / Mountain / Small / Yellow / Polish / 9%');
INSERT INTO part (partid, name) VALUES ('sd-m1sym', 'Saddle / Mountain / Small / Yellow / Matte / 9%');
INSERT INTO part (partid, name) VALUES ('fr-m1sym', 'Frame / Mountain / Small / Yellow / Matte / 9%');
INSERT INTO part (partid, name) VALUES ('wh-m1sym', 'Wheels / Mountain / Small / Yellow / Matte / 9%');
INSERT INTO part (partid, name) VALUES ('fs-m1sym', 'Front Set / Mountain / Small / Yellow / Matte / 9%');
INSERT INTO part (partid, name) VALUES ('pu-m1sym', 'Pedal Unit / Mountain / Small / Yellow / Matte / 9%');
INSERT INTO part (partid, name) VALUES ('sd-m1srp', 'Saddle / Mountain / Small / Red / Polish / 9%');
INSERT INTO part (partid, name) VALUES ('fr-m1srp', 'Frame / Mountain / Small / Red / Polish / 9%');
INSERT INTO part (partid, name) VALUES ('wh-m1srp', 'Wheels / Mountain / Small / Red / Polish / 9%');
INSERT INTO part (partid, name) VALUES ('fs-m1srp', 'Front Set / Mountain / Small / Red / Polish / 9%');
INSERT INTO part (partid, name) VALUES ('pu-m1srp', 'Pedal Unit / Mountain / Small / Red / Polish / 9%');
INSERT INTO part (partid, name) VALUES ('sd-m1srm', 'Saddle / Mountain / Small / Red / Matte / 9%');
INSERT INTO part (partid, name) VALUES ('fr-m1srm', 'Frame / Mountain / Small / Red / Matte / 9%');
INSERT INTO part (partid, name) VALUES ('wh-m1srm', 'Wheels / Mountain / Small / Red / Matte / 9%');
INSERT INTO part (partid, name) VALUES ('fs-m1srm', 'Front Set / Mountain / Small / Red / Matte / 9%');
INSERT INTO part (partid, name) VALUES ('pu-m1srm', 'Pedal Unit / Mountain / Small / Red / Matte / 9%');
INSERT INTO part (partid, name) VALUES ('sd-m1mnp', 'Saddle / Mountain / Medium / Black / Polish / 9%');
INSERT INTO part (partid, name) VALUES ('fr-m1mnp', 'Frame / Mountain / Medium / Black / Polish / 9%');
INSERT INTO part (partid, name) VALUES ('wh-m1mnp', 'Wheels / Mountain / Medium / Black / Polish / 9%');
INSERT INTO part (partid, name) VALUES ('fs-m1mnp', 'Front Set / Mountain / Medium / Black / Polish / 9%');
INSERT INTO part (partid, name) VALUES ('pu-m1mnp', 'Pedal Unit / Mountain / Medium / Black / Polish / 9%');
INSERT INTO part (partid, name) VALUES ('sd-m1mnm', 'Saddle / Mountain / Medium / Black / Matte / 9%');
INSERT INTO part (partid, name) VALUES ('fr-m1mnm', 'Frame / Mountain / Medium / Black / Matte / 9%');
INSERT INTO part (partid, name) VALUES ('wh-m1mnm', 'Wheels / Mountain / Medium / Black / Matte / 9%');
INSERT INTO part (partid, name) VALUES ('fs-m1mnm', 'Front Set / Mountain / Medium / Black / Matte / 9%');
INSERT INTO part (partid, name) VALUES ('pu-m1mnm', 'Pedal Unit / Mountain / Medium / Black / Matte / 9%');
INSERT INTO part (partid, name) VALUES ('sd-m1mwp', 'Saddle / Mountain / Medium / White / Polish / 9%');
INSERT INTO part (partid, name) VALUES ('fr-m1mwp', 'Frame / Mountain / Medium / White / Polish / 9%');
INSERT INTO part (partid, name) VALUES ('wh-m1mwp', 'Wheels / Mountain / Medium / White / Polish / 9%');
INSERT INTO part (partid, name) VALUES ('fs-m1mwp', 'Front Set / Mountain / Medium / White / Polish / 9%');
INSERT INTO part (partid, name) VALUES ('pu-m1mwp', 'Pedal Unit / Mountain / Medium / White / Polish / 9%');
INSERT INTO part (partid, name) VALUES ('sd-m1mwm', 'Saddle / Mountain / Medium / White / Matte / 9%');
INSERT INTO part (partid, name) VALUES ('fr-m1mwm', 'Frame / Mountain / Medium / White / Matte / 9%');
INSERT INTO part (partid, name) VALUES ('wh-m1mwm', 'Wheels / Mountain / Medium / White / Matte / 9%');
INSERT INTO part (partid, name) VALUES ('fs-m1mwm', 'Front Set / Mountain / Medium / White / Matte / 9%');
INSERT INTO part (partid, name) VALUES ('pu-m1mwm', 'Pedal Unit / Mountain / Medium / White / Matte / 9%');
INSERT INTO part (partid, name) VALUES ('sd-m1mbp', 'Saddle / Mountain / Medium / Blue / Polish / 9%');
INSERT INTO part (partid, name) VALUES ('fr-m1mbp', 'Frame / Mountain / Medium / Blue / Polish / 9%');
INSERT INTO part (partid, name) VALUES ('wh-m1mbp', 'Wheels / Mountain / Medium / Blue / Polish / 9%');
INSERT INTO part (partid, name) VALUES ('fs-m1mbp', 'Front Set / Mountain / Medium / Blue / Polish / 9%');
INSERT INTO part (partid, name) VALUES ('pu-m1mbp', 'Pedal Unit / Mountain / Medium / Blue / Polish / 9%');
INSERT INTO part (partid, name) VALUES ('sd-m1mbm', 'Saddle / Mountain / Medium / Blue / Matte / 9%');
INSERT INTO part (partid, name) VALUES ('fr-m1mbm', 'Frame / Mountain / Medium / Blue / Matte / 9%');
INSERT INTO part (partid, name) VALUES ('wh-m1mbm', 'Wheels / Mountain / Medium / Blue / Matte / 9%');
INSERT INTO part (partid, name) VALUES ('fs-m1mbm', 'Front Set / Mountain / Medium / Blue / Matte / 9%');
INSERT INTO part (partid, name) VALUES ('pu-m1mbm', 'Pedal Unit / Mountain / Medium / Blue / Matte / 9%');
INSERT INTO part (partid, name) VALUES ('sd-m1myp', 'Saddle / Mountain / Medium / Yellow / Polish / 9%');
INSERT INTO part (partid, name) VALUES ('fr-m1myp', 'Frame / Mountain / Medium / Yellow / Polish / 9%');
INSERT INTO part (partid, name) VALUES ('wh-m1myp', 'Wheels / Mountain / Medium / Yellow / Polish / 9%');
INSERT INTO part (partid, name) VALUES ('fs-m1myp', 'Front Set / Mountain / Medium / Yellow / Polish / 9%');
INSERT INTO part (partid, name) VALUES ('pu-m1myp', 'Pedal Unit / Mountain / Medium / Yellow / Polish / 9%');
INSERT INTO part (partid, name) VALUES ('sd-m1mym', 'Saddle / Mountain / Medium / Yellow / Matte / 9%');
INSERT INTO part (partid, name) VALUES ('fr-m1mym', 'Frame / Mountain / Medium / Yellow / Matte / 9%');
INSERT INTO part (partid, name) VALUES ('wh-m1mym', 'Wheels / Mountain / Medium / Yellow / Matte / 9%');
INSERT INTO part (partid, name) VALUES ('fs-m1mym', 'Front Set / Mountain / Medium / Yellow / Matte / 9%');
INSERT INTO part (partid, name) VALUES ('pu-m1mym', 'Pedal Unit / Mountain / Medium / Yellow / Matte / 9%');
INSERT INTO part (partid, name) VALUES ('sd-m1mrp', 'Saddle / Mountain / Medium / Red / Polish / 9%');
INSERT INTO part (partid, name) VALUES ('fr-m1mrp', 'Frame / Mountain / Medium / Red / Polish / 9%');
INSERT INTO part (partid, name) VALUES ('wh-m1mrp', 'Wheels / Mountain / Medium / Red / Polish / 9%');
INSERT INTO part (partid, name) VALUES ('fs-m1mrp', 'Front Set / Mountain / Medium / Red / Polish / 9%');
INSERT INTO part (partid, name) VALUES ('pu-m1mrp', 'Pedal Unit / Mountain / Medium / Red / Polish / 9%');
INSERT INTO part (partid, name) VALUES ('sd-m1mrm', 'Saddle / Mountain / Medium / Red / Matte / 9%');
INSERT INTO part (partid, name) VALUES ('fr-m1mrm', 'Frame / Mountain / Medium / Red / Matte / 9%');
INSERT INTO part (partid, name) VALUES ('wh-m1mrm', 'Wheels / Mountain / Medium / Red / Matte / 9%');
INSERT INTO part (partid, name) VALUES ('fs-m1mrm', 'Front Set / Mountain / Medium / Red / Matte / 9%');
INSERT INTO part (partid, name) VALUES ('pu-m1mrm', 'Pedal Unit / Mountain / Medium / Red / Matte / 9%');
INSERT INTO part (partid, name) VALUES ('sd-m1lnp', 'Saddle / Mountain / Large / Black / Polish / 9%');
INSERT INTO part (partid, name) VALUES ('fr-m1lnp', 'Frame / Mountain / Large / Black / Polish / 9%');
INSERT INTO part (partid, name) VALUES ('wh-m1lnp', 'Wheels / Mountain / Large / Black / Polish / 9%');
INSERT INTO part (partid, name) VALUES ('fs-m1lnp', 'Front Set / Mountain / Large / Black / Polish / 9%');
INSERT INTO part (partid, name) VALUES ('pu-m1lnp', 'Pedal Unit / Mountain / Large / Black / Polish / 9%');
INSERT INTO part (partid, name) VALUES ('sd-m1lnm', 'Saddle / Mountain / Large / Black / Matte / 9%');
INSERT INTO part (partid, name) VALUES ('fr-m1lnm', 'Frame / Mountain / Large / Black / Matte / 9%');
INSERT INTO part (partid, name) VALUES ('wh-m1lnm', 'Wheels / Mountain / Large / Black / Matte / 9%');
INSERT INTO part (partid, name) VALUES ('fs-m1lnm', 'Front Set / Mountain / Large / Black / Matte / 9%');
INSERT INTO part (partid, name) VALUES ('pu-m1lnm', 'Pedal Unit / Mountain / Large / Black / Matte / 9%');
INSERT INTO part (partid, name) VALUES ('sd-m1lwp', 'Saddle / Mountain / Large / White / Polish / 9%');
INSERT INTO part (partid, name) VALUES ('fr-m1lwp', 'Frame / Mountain / Large / White / Polish / 9%');
INSERT INTO part (partid, name) VALUES ('wh-m1lwp', 'Wheels / Mountain / Large / White / Polish / 9%');
INSERT INTO part (partid, name) VALUES ('fs-m1lwp', 'Front Set / Mountain / Large / White / Polish / 9%');
INSERT INTO part (partid, name) VALUES ('pu-m1lwp', 'Pedal Unit / Mountain / Large / White / Polish / 9%');
INSERT INTO part (partid, name) VALUES ('sd-m1lwm', 'Saddle / Mountain / Large / White / Matte / 9%');
INSERT INTO part (partid, name) VALUES ('fr-m1lwm', 'Frame / Mountain / Large / White / Matte / 9%');
INSERT INTO part (partid, name) VALUES ('wh-m1lwm', 'Wheels / Mountain / Large / White / Matte / 9%');
INSERT INTO part (partid, name) VALUES ('fs-m1lwm', 'Front Set / Mountain / Large / White / Matte / 9%');
INSERT INTO part (partid, name) VALUES ('pu-m1lwm', 'Pedal Unit / Mountain / Large / White / Matte / 9%');
INSERT INTO part (partid, name) VALUES ('sd-m1lbp', 'Saddle / Mountain / Large / Blue / Polish / 9%');
INSERT INTO part (partid, name) VALUES ('fr-m1lbp', 'Frame / Mountain / Large / Blue / Polish / 9%');
INSERT INTO part (partid, name) VALUES ('wh-m1lbp', 'Wheels / Mountain / Large / Blue / Polish / 9%');
INSERT INTO part (partid, name) VALUES ('fs-m1lbp', 'Front Set / Mountain / Large / Blue / Polish / 9%');
INSERT INTO part (partid, name) VALUES ('pu-m1lbp', 'Pedal Unit / Mountain / Large / Blue / Polish / 9%');
INSERT INTO part (partid, name) VALUES ('sd-m1lbm', 'Saddle / Mountain / Large / Blue / Matte / 9%');
INSERT INTO part (partid, name) VALUES ('fr-m1lbm', 'Frame / Mountain / Large / Blue / Matte / 9%');
INSERT INTO part (partid, name) VALUES ('wh-m1lbm', 'Wheels / Mountain / Large / Blue / Matte / 9%');
INSERT INTO part (partid, name) VALUES ('fs-m1lbm', 'Front Set / Mountain / Large / Blue / Matte / 9%');
INSERT INTO part (partid, name) VALUES ('pu-m1lbm', 'Pedal Unit / Mountain / Large / Blue / Matte / 9%');
INSERT INTO part (partid, name) VALUES ('sd-m1lyp', 'Saddle / Mountain / Large / Yellow / Polish / 9%');
INSERT INTO part (partid, name) VALUES ('fr-m1lyp', 'Frame / Mountain / Large / Yellow / Polish / 9%');
INSERT INTO part (partid, name) VALUES ('wh-m1lyp', 'Wheels / Mountain / Large / Yellow / Polish / 9%');
INSERT INTO part (partid, name) VALUES ('fs-m1lyp', 'Front Set / Mountain / Large / Yellow / Polish / 9%');
INSERT INTO part (partid, name) VALUES ('pu-m1lyp', 'Pedal Unit / Mountain / Large / Yellow / Polish / 9%');
INSERT INTO part (partid, name) VALUES ('sd-m1lym', 'Saddle / Mountain / Large / Yellow / Matte / 9%');
INSERT INTO part (partid, name) VALUES ('fr-m1lym', 'Frame / Mountain / Large / Yellow / Matte / 9%');
INSERT INTO part (partid, name) VALUES ('wh-m1lym', 'Wheels / Mountain / Large / Yellow / Matte / 9%');
INSERT INTO part (partid, name) VALUES ('fs-m1lym', 'Front Set / Mountain / Large / Yellow / Matte / 9%');
INSERT INTO part (partid, name) VALUES ('pu-m1lym', 'Pedal Unit / Mountain / Large / Yellow / Matte / 9%');
INSERT INTO part (partid, name) VALUES ('sd-m1lrp', 'Saddle / Mountain / Large / Red / Polish / 9%');
INSERT INTO part (partid, name) VALUES ('fr-m1lrp', 'Frame / Mountain / Large / Red / Polish / 9%');
INSERT INTO part (partid, name) VALUES ('wh-m1lrp', 'Wheels / Mountain / Large / Red / Polish / 9%');
INSERT INTO part (partid, name) VALUES ('fs-m1lrp', 'Front Set / Mountain / Large / Red / Polish / 9%');
INSERT INTO part (partid, name) VALUES ('pu-m1lrp', 'Pedal Unit / Mountain / Large / Red / Polish / 9%');
INSERT INTO part (partid, name) VALUES ('sd-m1lrm', 'Saddle / Mountain / Large / Red / Matte / 9%');
INSERT INTO part (partid, name) VALUES ('fr-m1lrm', 'Frame / Mountain / Large / Red / Matte / 9%');
INSERT INTO part (partid, name) VALUES ('wh-m1lrm', 'Wheels / Mountain / Large / Red / Matte / 9%');
INSERT INTO part (partid, name) VALUES ('fs-m1lrm', 'Front Set / Mountain / Large / Red / Matte / 9%');
INSERT INTO part (partid, name) VALUES ('pu-m1lrm', 'Pedal Unit / Mountain / Large / Red / Matte / 9%');
INSERT INTO part (partid, name) VALUES ('sd-m2snp', 'Saddle / Mountain / Small / Black / Polish / 8%');
INSERT INTO part (partid, name) VALUES ('fr-m2snp', 'Frame / Mountain / Small / Black / Polish / 8%');
INSERT INTO part (partid, name) VALUES ('wh-m2snp', 'Wheels / Mountain / Small / Black / Polish / 8%');
INSERT INTO part (partid, name) VALUES ('fs-m2snp', 'Front Set / Mountain / Small / Black / Polish / 8%');
INSERT INTO part (partid, name) VALUES ('pu-m2snp', 'Pedal Unit / Mountain / Small / Black / Polish / 8%');
INSERT INTO part (partid, name) VALUES ('sd-m2snm', 'Saddle / Mountain / Small / Black / Matte / 8%');
INSERT INTO part (partid, name) VALUES ('fr-m2snm', 'Frame / Mountain / Small / Black / Matte / 8%');
INSERT INTO part (partid, name) VALUES ('wh-m2snm', 'Wheels / Mountain / Small / Black / Matte / 8%');
INSERT INTO part (partid, name) VALUES ('fs-m2snm', 'Front Set / Mountain / Small / Black / Matte / 8%');
INSERT INTO part (partid, name) VALUES ('pu-m2snm', 'Pedal Unit / Mountain / Small / Black / Matte / 8%');
INSERT INTO part (partid, name) VALUES ('sd-m2swp', 'Saddle / Mountain / Small / White / Polish / 8%');
INSERT INTO part (partid, name) VALUES ('fr-m2swp', 'Frame / Mountain / Small / White / Polish / 8%');
INSERT INTO part (partid, name) VALUES ('wh-m2swp', 'Wheels / Mountain / Small / White / Polish / 8%');
INSERT INTO part (partid, name) VALUES ('fs-m2swp', 'Front Set / Mountain / Small / White / Polish / 8%');
INSERT INTO part (partid, name) VALUES ('pu-m2swp', 'Pedal Unit / Mountain / Small / White / Polish / 8%');
INSERT INTO part (partid, name) VALUES ('sd-m2swm', 'Saddle / Mountain / Small / White / Matte / 8%');
INSERT INTO part (partid, name) VALUES ('fr-m2swm', 'Frame / Mountain / Small / White / Matte / 8%');
INSERT INTO part (partid, name) VALUES ('wh-m2swm', 'Wheels / Mountain / Small / White / Matte / 8%');
INSERT INTO part (partid, name) VALUES ('fs-m2swm', 'Front Set / Mountain / Small / White / Matte / 8%');
INSERT INTO part (partid, name) VALUES ('pu-m2swm', 'Pedal Unit / Mountain / Small / White / Matte / 8%');
INSERT INTO part (partid, name) VALUES ('sd-m2sbp', 'Saddle / Mountain / Small / Blue / Polish / 8%');
INSERT INTO part (partid, name) VALUES ('fr-m2sbp', 'Frame / Mountain / Small / Blue / Polish / 8%');
INSERT INTO part (partid, name) VALUES ('wh-m2sbp', 'Wheels / Mountain / Small / Blue / Polish / 8%');
INSERT INTO part (partid, name) VALUES ('fs-m2sbp', 'Front Set / Mountain / Small / Blue / Polish / 8%');
INSERT INTO part (partid, name) VALUES ('pu-m2sbp', 'Pedal Unit / Mountain / Small / Blue / Polish / 8%');
INSERT INTO part (partid, name) VALUES ('sd-m2sbm', 'Saddle / Mountain / Small / Blue / Matte / 8%');
INSERT INTO part (partid, name) VALUES ('fr-m2sbm', 'Frame / Mountain / Small / Blue / Matte / 8%');
INSERT INTO part (partid, name) VALUES ('wh-m2sbm', 'Wheels / Mountain / Small / Blue / Matte / 8%');
INSERT INTO part (partid, name) VALUES ('fs-m2sbm', 'Front Set / Mountain / Small / Blue / Matte / 8%');
INSERT INTO part (partid, name) VALUES ('pu-m2sbm', 'Pedal Unit / Mountain / Small / Blue / Matte / 8%');
INSERT INTO part (partid, name) VALUES ('sd-m2syp', 'Saddle / Mountain / Small / Yellow / Polish / 8%');
INSERT INTO part (partid, name) VALUES ('fr-m2syp', 'Frame / Mountain / Small / Yellow / Polish / 8%');
INSERT INTO part (partid, name) VALUES ('wh-m2syp', 'Wheels / Mountain / Small / Yellow / Polish / 8%');
INSERT INTO part (partid, name) VALUES ('fs-m2syp', 'Front Set / Mountain / Small / Yellow / Polish / 8%');
INSERT INTO part (partid, name) VALUES ('pu-m2syp', 'Pedal Unit / Mountain / Small / Yellow / Polish / 8%');
INSERT INTO part (partid, name) VALUES ('sd-m2sym', 'Saddle / Mountain / Small / Yellow / Matte / 8%');
INSERT INTO part (partid, name) VALUES ('fr-m2sym', 'Frame / Mountain / Small / Yellow / Matte / 8%');
INSERT INTO part (partid, name) VALUES ('wh-m2sym', 'Wheels / Mountain / Small / Yellow / Matte / 8%');
INSERT INTO part (partid, name) VALUES ('fs-m2sym', 'Front Set / Mountain / Small / Yellow / Matte / 8%');
INSERT INTO part (partid, name) VALUES ('pu-m2sym', 'Pedal Unit / Mountain / Small / Yellow / Matte / 8%');
INSERT INTO part (partid, name) VALUES ('sd-m2srp', 'Saddle / Mountain / Small / Red / Polish / 8%');
INSERT INTO part (partid, name) VALUES ('fr-m2srp', 'Frame / Mountain / Small / Red / Polish / 8%');
INSERT INTO part (partid, name) VALUES ('wh-m2srp', 'Wheels / Mountain / Small / Red / Polish / 8%');
INSERT INTO part (partid, name) VALUES ('fs-m2srp', 'Front Set / Mountain / Small / Red / Polish / 8%');
INSERT INTO part (partid, name) VALUES ('pu-m2srp', 'Pedal Unit / Mountain / Small / Red / Polish / 8%');
INSERT INTO part (partid, name) VALUES ('sd-m2srm', 'Saddle / Mountain / Small / Red / Matte / 8%');
INSERT INTO part (partid, name) VALUES ('fr-m2srm', 'Frame / Mountain / Small / Red / Matte / 8%');
INSERT INTO part (partid, name) VALUES ('wh-m2srm', 'Wheels / Mountain / Small / Red / Matte / 8%');
INSERT INTO part (partid, name) VALUES ('fs-m2srm', 'Front Set / Mountain / Small / Red / Matte / 8%');
INSERT INTO part (partid, name) VALUES ('pu-m2srm', 'Pedal Unit / Mountain / Small / Red / Matte / 8%');
INSERT INTO part (partid, name) VALUES ('sd-m2mnp', 'Saddle / Mountain / Medium / Black / Polish / 8%');
INSERT INTO part (partid, name) VALUES ('fr-m2mnp', 'Frame / Mountain / Medium / Black / Polish / 8%');
INSERT INTO part (partid, name) VALUES ('wh-m2mnp', 'Wheels / Mountain / Medium / Black / Polish / 8%');
INSERT INTO part (partid, name) VALUES ('fs-m2mnp', 'Front Set / Mountain / Medium / Black / Polish / 8%');
INSERT INTO part (partid, name) VALUES ('pu-m2mnp', 'Pedal Unit / Mountain / Medium / Black / Polish / 8%');
INSERT INTO part (partid, name) VALUES ('sd-m2mnm', 'Saddle / Mountain / Medium / Black / Matte / 8%');
INSERT INTO part (partid, name) VALUES ('fr-m2mnm', 'Frame / Mountain / Medium / Black / Matte / 8%');
INSERT INTO part (partid, name) VALUES ('wh-m2mnm', 'Wheels / Mountain / Medium / Black / Matte / 8%');
INSERT INTO part (partid, name) VALUES ('fs-m2mnm', 'Front Set / Mountain / Medium / Black / Matte / 8%');
INSERT INTO part (partid, name) VALUES ('pu-m2mnm', 'Pedal Unit / Mountain / Medium / Black / Matte / 8%');
INSERT INTO part (partid, name) VALUES ('sd-m2mwp', 'Saddle / Mountain / Medium / White / Polish / 8%');
INSERT INTO part (partid, name) VALUES ('fr-m2mwp', 'Frame / Mountain / Medium / White / Polish / 8%');
INSERT INTO part (partid, name) VALUES ('wh-m2mwp', 'Wheels / Mountain / Medium / White / Polish / 8%');
INSERT INTO part (partid, name) VALUES ('fs-m2mwp', 'Front Set / Mountain / Medium / White / Polish / 8%');
INSERT INTO part (partid, name) VALUES ('pu-m2mwp', 'Pedal Unit / Mountain / Medium / White / Polish / 8%');
INSERT INTO part (partid, name) VALUES ('sd-m2mwm', 'Saddle / Mountain / Medium / White / Matte / 8%');
INSERT INTO part (partid, name) VALUES ('fr-m2mwm', 'Frame / Mountain / Medium / White / Matte / 8%');
INSERT INTO part (partid, name) VALUES ('wh-m2mwm', 'Wheels / Mountain / Medium / White / Matte / 8%');
INSERT INTO part (partid, name) VALUES ('fs-m2mwm', 'Front Set / Mountain / Medium / White / Matte / 8%');
INSERT INTO part (partid, name) VALUES ('pu-m2mwm', 'Pedal Unit / Mountain / Medium / White / Matte / 8%');
INSERT INTO part (partid, name) VALUES ('sd-m2mbp', 'Saddle / Mountain / Medium / Blue / Polish / 8%');
INSERT INTO part (partid, name) VALUES ('fr-m2mbp', 'Frame / Mountain / Medium / Blue / Polish / 8%');
INSERT INTO part (partid, name) VALUES ('wh-m2mbp', 'Wheels / Mountain / Medium / Blue / Polish / 8%');
INSERT INTO part (partid, name) VALUES ('fs-m2mbp', 'Front Set / Mountain / Medium / Blue / Polish / 8%');
INSERT INTO part (partid, name) VALUES ('pu-m2mbp', 'Pedal Unit / Mountain / Medium / Blue / Polish / 8%');
INSERT INTO part (partid, name) VALUES ('sd-m2mbm', 'Saddle / Mountain / Medium / Blue / Matte / 8%');
INSERT INTO part (partid, name) VALUES ('fr-m2mbm', 'Frame / Mountain / Medium / Blue / Matte / 8%');
INSERT INTO part (partid, name) VALUES ('wh-m2mbm', 'Wheels / Mountain / Medium / Blue / Matte / 8%');
INSERT INTO part (partid, name) VALUES ('fs-m2mbm', 'Front Set / Mountain / Medium / Blue / Matte / 8%');
INSERT INTO part (partid, name) VALUES ('pu-m2mbm', 'Pedal Unit / Mountain / Medium / Blue / Matte / 8%');
INSERT INTO part (partid, name) VALUES ('sd-m2myp', 'Saddle / Mountain / Medium / Yellow / Polish / 8%');
INSERT INTO part (partid, name) VALUES ('fr-m2myp', 'Frame / Mountain / Medium / Yellow / Polish / 8%');
INSERT INTO part (partid, name) VALUES ('wh-m2myp', 'Wheels / Mountain / Medium / Yellow / Polish / 8%');
INSERT INTO part (partid, name) VALUES ('fs-m2myp', 'Front Set / Mountain / Medium / Yellow / Polish / 8%');
INSERT INTO part (partid, name) VALUES ('pu-m2myp', 'Pedal Unit / Mountain / Medium / Yellow / Polish / 8%');
INSERT INTO part (partid, name) VALUES ('sd-m2mym', 'Saddle / Mountain / Medium / Yellow / Matte / 8%');
INSERT INTO part (partid, name) VALUES ('fr-m2mym', 'Frame / Mountain / Medium / Yellow / Matte / 8%');
INSERT INTO part (partid, name) VALUES ('wh-m2mym', 'Wheels / Mountain / Medium / Yellow / Matte / 8%');
INSERT INTO part (partid, name) VALUES ('fs-m2mym', 'Front Set / Mountain / Medium / Yellow / Matte / 8%');
INSERT INTO part (partid, name) VALUES ('pu-m2mym', 'Pedal Unit / Mountain / Medium / Yellow / Matte / 8%');
INSERT INTO part (partid, name) VALUES ('sd-m2mrp', 'Saddle / Mountain / Medium / Red / Polish / 8%');
INSERT INTO part (partid, name) VALUES ('fr-m2mrp', 'Frame / Mountain / Medium / Red / Polish / 8%');
INSERT INTO part (partid, name) VALUES ('wh-m2mrp', 'Wheels / Mountain / Medium / Red / Polish / 8%');
INSERT INTO part (partid, name) VALUES ('fs-m2mrp', 'Front Set / Mountain / Medium / Red / Polish / 8%');
INSERT INTO part (partid, name) VALUES ('pu-m2mrp', 'Pedal Unit / Mountain / Medium / Red / Polish / 8%');
INSERT INTO part (partid, name) VALUES ('sd-m2mrm', 'Saddle / Mountain / Medium / Red / Matte / 8%');
INSERT INTO part (partid, name) VALUES ('fr-m2mrm', 'Frame / Mountain / Medium / Red / Matte / 8%');
INSERT INTO part (partid, name) VALUES ('wh-m2mrm', 'Wheels / Mountain / Medium / Red / Matte / 8%');
INSERT INTO part (partid, name) VALUES ('fs-m2mrm', 'Front Set / Mountain / Medium / Red / Matte / 8%');
INSERT INTO part (partid, name) VALUES ('pu-m2mrm', 'Pedal Unit / Mountain / Medium / Red / Matte / 8%');
INSERT INTO part (partid, name) VALUES ('sd-m2lnp', 'Saddle / Mountain / Large / Black / Polish / 8%');
INSERT INTO part (partid, name) VALUES ('fr-m2lnp', 'Frame / Mountain / Large / Black / Polish / 8%');
INSERT INTO part (partid, name) VALUES ('wh-m2lnp', 'Wheels / Mountain / Large / Black / Polish / 8%');
INSERT INTO part (partid, name) VALUES ('fs-m2lnp', 'Front Set / Mountain / Large / Black / Polish / 8%');
INSERT INTO part (partid, name) VALUES ('pu-m2lnp', 'Pedal Unit / Mountain / Large / Black / Polish / 8%');
INSERT INTO part (partid, name) VALUES ('sd-m2lnm', 'Saddle / Mountain / Large / Black / Matte / 8%');
INSERT INTO part (partid, name) VALUES ('fr-m2lnm', 'Frame / Mountain / Large / Black / Matte / 8%');
INSERT INTO part (partid, name) VALUES ('wh-m2lnm', 'Wheels / Mountain / Large / Black / Matte / 8%');
INSERT INTO part (partid, name) VALUES ('fs-m2lnm', 'Front Set / Mountain / Large / Black / Matte / 8%');
INSERT INTO part (partid, name) VALUES ('pu-m2lnm', 'Pedal Unit / Mountain / Large / Black / Matte / 8%');
INSERT INTO part (partid, name) VALUES ('sd-m2lwp', 'Saddle / Mountain / Large / White / Polish / 8%');
INSERT INTO part (partid, name) VALUES ('fr-m2lwp', 'Frame / Mountain / Large / White / Polish / 8%');
INSERT INTO part (partid, name) VALUES ('wh-m2lwp', 'Wheels / Mountain / Large / White / Polish / 8%');
INSERT INTO part (partid, name) VALUES ('fs-m2lwp', 'Front Set / Mountain / Large / White / Polish / 8%');
INSERT INTO part (partid, name) VALUES ('pu-m2lwp', 'Pedal Unit / Mountain / Large / White / Polish / 8%');
INSERT INTO part (partid, name) VALUES ('sd-m2lwm', 'Saddle / Mountain / Large / White / Matte / 8%');
INSERT INTO part (partid, name) VALUES ('fr-m2lwm', 'Frame / Mountain / Large / White / Matte / 8%');
INSERT INTO part (partid, name) VALUES ('wh-m2lwm', 'Wheels / Mountain / Large / White / Matte / 8%');
INSERT INTO part (partid, name) VALUES ('fs-m2lwm', 'Front Set / Mountain / Large / White / Matte / 8%');
INSERT INTO part (partid, name) VALUES ('pu-m2lwm', 'Pedal Unit / Mountain / Large / White / Matte / 8%');
INSERT INTO part (partid, name) VALUES ('sd-m2lbp', 'Saddle / Mountain / Large / Blue / Polish / 8%');
INSERT INTO part (partid, name) VALUES ('fr-m2lbp', 'Frame / Mountain / Large / Blue / Polish / 8%');
INSERT INTO part (partid, name) VALUES ('wh-m2lbp', 'Wheels / Mountain / Large / Blue / Polish / 8%');
INSERT INTO part (partid, name) VALUES ('fs-m2lbp', 'Front Set / Mountain / Large / Blue / Polish / 8%');
INSERT INTO part (partid, name) VALUES ('pu-m2lbp', 'Pedal Unit / Mountain / Large / Blue / Polish / 8%');
INSERT INTO part (partid, name) VALUES ('sd-m2lbm', 'Saddle / Mountain / Large / Blue / Matte / 8%');
INSERT INTO part (partid, name) VALUES ('fr-m2lbm', 'Frame / Mountain / Large / Blue / Matte / 8%');
INSERT INTO part (partid, name) VALUES ('wh-m2lbm', 'Wheels / Mountain / Large / Blue / Matte / 8%');
INSERT INTO part (partid, name) VALUES ('fs-m2lbm', 'Front Set / Mountain / Large / Blue / Matte / 8%');
INSERT INTO part (partid, name) VALUES ('pu-m2lbm', 'Pedal Unit / Mountain / Large / Blue / Matte / 8%');
INSERT INTO part (partid, name) VALUES ('sd-m2lyp', 'Saddle / Mountain / Large / Yellow / Polish / 8%');
INSERT INTO part (partid, name) VALUES ('fr-m2lyp', 'Frame / Mountain / Large / Yellow / Polish / 8%');
INSERT INTO part (partid, name) VALUES ('wh-m2lyp', 'Wheels / Mountain / Large / Yellow / Polish / 8%');
INSERT INTO part (partid, name) VALUES ('fs-m2lyp', 'Front Set / Mountain / Large / Yellow / Polish / 8%');
INSERT INTO part (partid, name) VALUES ('pu-m2lyp', 'Pedal Unit / Mountain / Large / Yellow / Polish / 8%');
INSERT INTO part (partid, name) VALUES ('sd-m2lym', 'Saddle / Mountain / Large / Yellow / Matte / 8%');
INSERT INTO part (partid, name) VALUES ('fr-m2lym', 'Frame / Mountain / Large / Yellow / Matte / 8%');
INSERT INTO part (partid, name) VALUES ('wh-m2lym', 'Wheels / Mountain / Large / Yellow / Matte / 8%');
INSERT INTO part (partid, name) VALUES ('fs-m2lym', 'Front Set / Mountain / Large / Yellow / Matte / 8%');
INSERT INTO part (partid, name) VALUES ('pu-m2lym', 'Pedal Unit / Mountain / Large / Yellow / Matte / 8%');
INSERT INTO part (partid, name) VALUES ('sd-m2lrp', 'Saddle / Mountain / Large / Red / Polish / 8%');
INSERT INTO part (partid, name) VALUES ('fr-m2lrp', 'Frame / Mountain / Large / Red / Polish / 8%');
INSERT INTO part (partid, name) VALUES ('wh-m2lrp', 'Wheels / Mountain / Large / Red / Polish / 8%');
INSERT INTO part (partid, name) VALUES ('fs-m2lrp', 'Front Set / Mountain / Large / Red / Polish / 8%');
INSERT INTO part (partid, name) VALUES ('pu-m2lrp', 'Pedal Unit / Mountain / Large / Red / Polish / 8%');
INSERT INTO part (partid, name) VALUES ('sd-m2lrm', 'Saddle / Mountain / Large / Red / Matte / 8%');
INSERT INTO part (partid, name) VALUES ('fr-m2lrm', 'Frame / Mountain / Large / Red / Matte / 8%');
INSERT INTO part (partid, name) VALUES ('wh-m2lrm', 'Wheels / Mountain / Large / Red / Matte / 8%');
INSERT INTO part (partid, name) VALUES ('fs-m2lrm', 'Front Set / Mountain / Large / Red / Matte / 8%');
INSERT INTO part (partid, name) VALUES ('pu-m2lrm', 'Pedal Unit / Mountain / Large / Red / Matte / 8%');
INSERT INTO part (partid, name) VALUES ('sd-r1snp', 'Saddle / Road / Small / Black / Polish / 5%');
INSERT INTO part (partid, name) VALUES ('fr-r1snp', 'Frame / Road / Small / Black / Polish / 5%');
INSERT INTO part (partid, name) VALUES ('wh-r1snp', 'Wheels / Road / Small / Black / Polish / 5%');
INSERT INTO part (partid, name) VALUES ('fs-r1snp', 'Front Set / Road / Small / Black / Polish / 5%');
INSERT INTO part (partid, name) VALUES ('pu-r1snp', 'Pedal Unit / Road / Small / Black / Polish / 5%');
INSERT INTO part (partid, name) VALUES ('sd-r1snm', 'Saddle / Road / Small / Black / Matte / 5%');
INSERT INTO part (partid, name) VALUES ('fr-r1snm', 'Frame / Road / Small / Black / Matte / 5%');
INSERT INTO part (partid, name) VALUES ('wh-r1snm', 'Wheels / Road / Small / Black / Matte / 5%');
INSERT INTO part (partid, name) VALUES ('fs-r1snm', 'Front Set / Road / Small / Black / Matte / 5%');
INSERT INTO part (partid, name) VALUES ('pu-r1snm', 'Pedal Unit / Road / Small / Black / Matte / 5%');
INSERT INTO part (partid, name) VALUES ('sd-r1swp', 'Saddle / Road / Small / White / Polish / 5%');
INSERT INTO part (partid, name) VALUES ('fr-r1swp', 'Frame / Road / Small / White / Polish / 5%');
INSERT INTO part (partid, name) VALUES ('wh-r1swp', 'Wheels / Road / Small / White / Polish / 5%');
INSERT INTO part (partid, name) VALUES ('fs-r1swp', 'Front Set / Road / Small / White / Polish / 5%');
INSERT INTO part (partid, name) VALUES ('pu-r1swp', 'Pedal Unit / Road / Small / White / Polish / 5%');
INSERT INTO part (partid, name) VALUES ('sd-r1swm', 'Saddle / Road / Small / White / Matte / 5%');
INSERT INTO part (partid, name) VALUES ('fr-r1swm', 'Frame / Road / Small / White / Matte / 5%');
INSERT INTO part (partid, name) VALUES ('wh-r1swm', 'Wheels / Road / Small / White / Matte / 5%');
INSERT INTO part (partid, name) VALUES ('fs-r1swm', 'Front Set / Road / Small / White / Matte / 5%');
INSERT INTO part (partid, name) VALUES ('pu-r1swm', 'Pedal Unit / Road / Small / White / Matte / 5%');
INSERT INTO part (partid, name) VALUES ('sd-r1sbp', 'Saddle / Road / Small / Blue / Polish / 5%');
INSERT INTO part (partid, name) VALUES ('fr-r1sbp', 'Frame / Road / Small / Blue / Polish / 5%');
INSERT INTO part (partid, name) VALUES ('wh-r1sbp', 'Wheels / Road / Small / Blue / Polish / 5%');
INSERT INTO part (partid, name) VALUES ('fs-r1sbp', 'Front Set / Road / Small / Blue / Polish / 5%');
INSERT INTO part (partid, name) VALUES ('pu-r1sbp', 'Pedal Unit / Road / Small / Blue / Polish / 5%');
INSERT INTO part (partid, name) VALUES ('sd-r1sbm', 'Saddle / Road / Small / Blue / Matte / 5%');
INSERT INTO part (partid, name) VALUES ('fr-r1sbm', 'Frame / Road / Small / Blue / Matte / 5%');
INSERT INTO part (partid, name) VALUES ('wh-r1sbm', 'Wheels / Road / Small / Blue / Matte / 5%');
INSERT INTO part (partid, name) VALUES ('fs-r1sbm', 'Front Set / Road / Small / Blue / Matte / 5%');
INSERT INTO part (partid, name) VALUES ('pu-r1sbm', 'Pedal Unit / Road / Small / Blue / Matte / 5%');
INSERT INTO part (partid, name) VALUES ('sd-r1syp', 'Saddle / Road / Small / Yellow / Polish / 5%');
INSERT INTO part (partid, name) VALUES ('fr-r1syp', 'Frame / Road / Small / Yellow / Polish / 5%');
INSERT INTO part (partid, name) VALUES ('wh-r1syp', 'Wheels / Road / Small / Yellow / Polish / 5%');
INSERT INTO part (partid, name) VALUES ('fs-r1syp', 'Front Set / Road / Small / Yellow / Polish / 5%');
INSERT INTO part (partid, name) VALUES ('pu-r1syp', 'Pedal Unit / Road / Small / Yellow / Polish / 5%');
INSERT INTO part (partid, name) VALUES ('sd-r1sym', 'Saddle / Road / Small / Yellow / Matte / 5%');
INSERT INTO part (partid, name) VALUES ('fr-r1sym', 'Frame / Road / Small / Yellow / Matte / 5%');
INSERT INTO part (partid, name) VALUES ('wh-r1sym', 'Wheels / Road / Small / Yellow / Matte / 5%');
INSERT INTO part (partid, name) VALUES ('fs-r1sym', 'Front Set / Road / Small / Yellow / Matte / 5%');
INSERT INTO part (partid, name) VALUES ('pu-r1sym', 'Pedal Unit / Road / Small / Yellow / Matte / 5%');
INSERT INTO part (partid, name) VALUES ('sd-r1srp', 'Saddle / Road / Small / Red / Polish / 5%');
INSERT INTO part (partid, name) VALUES ('fr-r1srp', 'Frame / Road / Small / Red / Polish / 5%');
INSERT INTO part (partid, name) VALUES ('wh-r1srp', 'Wheels / Road / Small / Red / Polish / 5%');
INSERT INTO part (partid, name) VALUES ('fs-r1srp', 'Front Set / Road / Small / Red / Polish / 5%');
INSERT INTO part (partid, name) VALUES ('pu-r1srp', 'Pedal Unit / Road / Small / Red / Polish / 5%');
INSERT INTO part (partid, name) VALUES ('sd-r1srm', 'Saddle / Road / Small / Red / Matte / 5%');
INSERT INTO part (partid, name) VALUES ('fr-r1srm', 'Frame / Road / Small / Red / Matte / 5%');
INSERT INTO part (partid, name) VALUES ('wh-r1srm', 'Wheels / Road / Small / Red / Matte / 5%');
INSERT INTO part (partid, name) VALUES ('fs-r1srm', 'Front Set / Road / Small / Red / Matte / 5%');
INSERT INTO part (partid, name) VALUES ('pu-r1srm', 'Pedal Unit / Road / Small / Red / Matte / 5%');
INSERT INTO part (partid, name) VALUES ('sd-r1mnp', 'Saddle / Road / Medium / Black / Polish / 5%');
INSERT INTO part (partid, name) VALUES ('fr-r1mnp', 'Frame / Road / Medium / Black / Polish / 5%');
INSERT INTO part (partid, name) VALUES ('wh-r1mnp', 'Wheels / Road / Medium / Black / Polish / 5%');
INSERT INTO part (partid, name) VALUES ('fs-r1mnp', 'Front Set / Road / Medium / Black / Polish / 5%');
INSERT INTO part (partid, name) VALUES ('pu-r1mnp', 'Pedal Unit / Road / Medium / Black / Polish / 5%');
INSERT INTO part (partid, name) VALUES ('sd-r1mnm', 'Saddle / Road / Medium / Black / Matte / 5%');
INSERT INTO part (partid, name) VALUES ('fr-r1mnm', 'Frame / Road / Medium / Black / Matte / 5%');
INSERT INTO part (partid, name) VALUES ('wh-r1mnm', 'Wheels / Road / Medium / Black / Matte / 5%');
INSERT INTO part (partid, name) VALUES ('fs-r1mnm', 'Front Set / Road / Medium / Black / Matte / 5%');
INSERT INTO part (partid, name) VALUES ('pu-r1mnm', 'Pedal Unit / Road / Medium / Black / Matte / 5%');
INSERT INTO part (partid, name) VALUES ('sd-r1mwp', 'Saddle / Road / Medium / White / Polish / 5%');
INSERT INTO part (partid, name) VALUES ('fr-r1mwp', 'Frame / Road / Medium / White / Polish / 5%');
INSERT INTO part (partid, name) VALUES ('wh-r1mwp', 'Wheels / Road / Medium / White / Polish / 5%');
INSERT INTO part (partid, name) VALUES ('fs-r1mwp', 'Front Set / Road / Medium / White / Polish / 5%');
INSERT INTO part (partid, name) VALUES ('pu-r1mwp', 'Pedal Unit / Road / Medium / White / Polish / 5%');
INSERT INTO part (partid, name) VALUES ('sd-r1mwm', 'Saddle / Road / Medium / White / Matte / 5%');
INSERT INTO part (partid, name) VALUES ('fr-r1mwm', 'Frame / Road / Medium / White / Matte / 5%');
INSERT INTO part (partid, name) VALUES ('wh-r1mwm', 'Wheels / Road / Medium / White / Matte / 5%');
INSERT INTO part (partid, name) VALUES ('fs-r1mwm', 'Front Set / Road / Medium / White / Matte / 5%');
INSERT INTO part (partid, name) VALUES ('pu-r1mwm', 'Pedal Unit / Road / Medium / White / Matte / 5%');
INSERT INTO part (partid, name) VALUES ('sd-r1mbp', 'Saddle / Road / Medium / Blue / Polish / 5%');
INSERT INTO part (partid, name) VALUES ('fr-r1mbp', 'Frame / Road / Medium / Blue / Polish / 5%');
INSERT INTO part (partid, name) VALUES ('wh-r1mbp', 'Wheels / Road / Medium / Blue / Polish / 5%');
INSERT INTO part (partid, name) VALUES ('fs-r1mbp', 'Front Set / Road / Medium / Blue / Polish / 5%');
INSERT INTO part (partid, name) VALUES ('pu-r1mbp', 'Pedal Unit / Road / Medium / Blue / Polish / 5%');
INSERT INTO part (partid, name) VALUES ('sd-r1mbm', 'Saddle / Road / Medium / Blue / Matte / 5%');
INSERT INTO part (partid, name) VALUES ('fr-r1mbm', 'Frame / Road / Medium / Blue / Matte / 5%');
INSERT INTO part (partid, name) VALUES ('wh-r1mbm', 'Wheels / Road / Medium / Blue / Matte / 5%');
INSERT INTO part (partid, name) VALUES ('fs-r1mbm', 'Front Set / Road / Medium / Blue / Matte / 5%');
INSERT INTO part (partid, name) VALUES ('pu-r1mbm', 'Pedal Unit / Road / Medium / Blue / Matte / 5%');
INSERT INTO part (partid, name) VALUES ('sd-r1myp', 'Saddle / Road / Medium / Yellow / Polish / 5%');
INSERT INTO part (partid, name) VALUES ('fr-r1myp', 'Frame / Road / Medium / Yellow / Polish / 5%');
INSERT INTO part (partid, name) VALUES ('wh-r1myp', 'Wheels / Road / Medium / Yellow / Polish / 5%');
INSERT INTO part (partid, name) VALUES ('fs-r1myp', 'Front Set / Road / Medium / Yellow / Polish / 5%');
INSERT INTO part (partid, name) VALUES ('pu-r1myp', 'Pedal Unit / Road / Medium / Yellow / Polish / 5%');
INSERT INTO part (partid, name) VALUES ('sd-r1mym', 'Saddle / Road / Medium / Yellow / Matte / 5%');
INSERT INTO part (partid, name) VALUES ('fr-r1mym', 'Frame / Road / Medium / Yellow / Matte / 5%');
INSERT INTO part (partid, name) VALUES ('wh-r1mym', 'Wheels / Road / Medium / Yellow / Matte / 5%');
INSERT INTO part (partid, name) VALUES ('fs-r1mym', 'Front Set / Road / Medium / Yellow / Matte / 5%');
INSERT INTO part (partid, name) VALUES ('pu-r1mym', 'Pedal Unit / Road / Medium / Yellow / Matte / 5%');
INSERT INTO part (partid, name) VALUES ('sd-r1mrp', 'Saddle / Road / Medium / Red / Polish / 5%');
INSERT INTO part (partid, name) VALUES ('fr-r1mrp', 'Frame / Road / Medium / Red / Polish / 5%');
INSERT INTO part (partid, name) VALUES ('wh-r1mrp', 'Wheels / Road / Medium / Red / Polish / 5%');
INSERT INTO part (partid, name) VALUES ('fs-r1mrp', 'Front Set / Road / Medium / Red / Polish / 5%');
INSERT INTO part (partid, name) VALUES ('pu-r1mrp', 'Pedal Unit / Road / Medium / Red / Polish / 5%');
INSERT INTO part (partid, name) VALUES ('sd-r1mrm', 'Saddle / Road / Medium / Red / Matte / 5%');
INSERT INTO part (partid, name) VALUES ('fr-r1mrm', 'Frame / Road / Medium / Red / Matte / 5%');
INSERT INTO part (partid, name) VALUES ('wh-r1mrm', 'Wheels / Road / Medium / Red / Matte / 5%');
INSERT INTO part (partid, name) VALUES ('fs-r1mrm', 'Front Set / Road / Medium / Red / Matte / 5%');
INSERT INTO part (partid, name) VALUES ('pu-r1mrm', 'Pedal Unit / Road / Medium / Red / Matte / 5%');
INSERT INTO part (partid, name) VALUES ('sd-r1lnp', 'Saddle / Road / Large / Black / Polish / 5%');
INSERT INTO part (partid, name) VALUES ('fr-r1lnp', 'Frame / Road / Large / Black / Polish / 5%');
INSERT INTO part (partid, name) VALUES ('wh-r1lnp', 'Wheels / Road / Large / Black / Polish / 5%');
INSERT INTO part (partid, name) VALUES ('fs-r1lnp', 'Front Set / Road / Large / Black / Polish / 5%');
INSERT INTO part (partid, name) VALUES ('pu-r1lnp', 'Pedal Unit / Road / Large / Black / Polish / 5%');
INSERT INTO part (partid, name) VALUES ('sd-r1lnm', 'Saddle / Road / Large / Black / Matte / 5%');
INSERT INTO part (partid, name) VALUES ('fr-r1lnm', 'Frame / Road / Large / Black / Matte / 5%');
INSERT INTO part (partid, name) VALUES ('wh-r1lnm', 'Wheels / Road / Large / Black / Matte / 5%');
INSERT INTO part (partid, name) VALUES ('fs-r1lnm', 'Front Set / Road / Large / Black / Matte / 5%');
INSERT INTO part (partid, name) VALUES ('pu-r1lnm', 'Pedal Unit / Road / Large / Black / Matte / 5%');
INSERT INTO part (partid, name) VALUES ('sd-r1lwp', 'Saddle / Road / Large / White / Polish / 5%');
INSERT INTO part (partid, name) VALUES ('fr-r1lwp', 'Frame / Road / Large / White / Polish / 5%');
INSERT INTO part (partid, name) VALUES ('wh-r1lwp', 'Wheels / Road / Large / White / Polish / 5%');
INSERT INTO part (partid, name) VALUES ('fs-r1lwp', 'Front Set / Road / Large / White / Polish / 5%');
INSERT INTO part (partid, name) VALUES ('pu-r1lwp', 'Pedal Unit / Road / Large / White / Polish / 5%');
INSERT INTO part (partid, name) VALUES ('sd-r1lwm', 'Saddle / Road / Large / White / Matte / 5%');
INSERT INTO part (partid, name) VALUES ('fr-r1lwm', 'Frame / Road / Large / White / Matte / 5%');
INSERT INTO part (partid, name) VALUES ('wh-r1lwm', 'Wheels / Road / Large / White / Matte / 5%');
INSERT INTO part (partid, name) VALUES ('fs-r1lwm', 'Front Set / Road / Large / White / Matte / 5%');
INSERT INTO part (partid, name) VALUES ('pu-r1lwm', 'Pedal Unit / Road / Large / White / Matte / 5%');
INSERT INTO part (partid, name) VALUES ('sd-r1lbp', 'Saddle / Road / Large / Blue / Polish / 5%');
INSERT INTO part (partid, name) VALUES ('fr-r1lbp', 'Frame / Road / Large / Blue / Polish / 5%');
INSERT INTO part (partid, name) VALUES ('wh-r1lbp', 'Wheels / Road / Large / Blue / Polish / 5%');
INSERT INTO part (partid, name) VALUES ('fs-r1lbp', 'Front Set / Road / Large / Blue / Polish / 5%');
INSERT INTO part (partid, name) VALUES ('pu-r1lbp', 'Pedal Unit / Road / Large / Blue / Polish / 5%');
INSERT INTO part (partid, name) VALUES ('sd-r1lbm', 'Saddle / Road / Large / Blue / Matte / 5%');
INSERT INTO part (partid, name) VALUES ('fr-r1lbm', 'Frame / Road / Large / Blue / Matte / 5%');
INSERT INTO part (partid, name) VALUES ('wh-r1lbm', 'Wheels / Road / Large / Blue / Matte / 5%');
INSERT INTO part (partid, name) VALUES ('fs-r1lbm', 'Front Set / Road / Large / Blue / Matte / 5%');
INSERT INTO part (partid, name) VALUES ('pu-r1lbm', 'Pedal Unit / Road / Large / Blue / Matte / 5%');
INSERT INTO part (partid, name) VALUES ('sd-r1lyp', 'Saddle / Road / Large / Yellow / Polish / 5%');
INSERT INTO part (partid, name) VALUES ('fr-r1lyp', 'Frame / Road / Large / Yellow / Polish / 5%');
INSERT INTO part (partid, name) VALUES ('wh-r1lyp', 'Wheels / Road / Large / Yellow / Polish / 5%');
INSERT INTO part (partid, name) VALUES ('fs-r1lyp', 'Front Set / Road / Large / Yellow / Polish / 5%');
INSERT INTO part (partid, name) VALUES ('pu-r1lyp', 'Pedal Unit / Road / Large / Yellow / Polish / 5%');
INSERT INTO part (partid, name) VALUES ('sd-r1lym', 'Saddle / Road / Large / Yellow / Matte / 5%');
INSERT INTO part (partid, name) VALUES ('fr-r1lym', 'Frame / Road / Large / Yellow / Matte / 5%');
INSERT INTO part (partid, name) VALUES ('wh-r1lym', 'Wheels / Road / Large / Yellow / Matte / 5%');
INSERT INTO part (partid, name) VALUES ('fs-r1lym', 'Front Set / Road / Large / Yellow / Matte / 5%');
INSERT INTO part (partid, name) VALUES ('pu-r1lym', 'Pedal Unit / Road / Large / Yellow / Matte / 5%');
INSERT INTO part (partid, name) VALUES ('sd-r1lrp', 'Saddle / Road / Large / Red / Polish / 5%');
INSERT INTO part (partid, name) VALUES ('fr-r1lrp', 'Frame / Road / Large / Red / Polish / 5%');
INSERT INTO part (partid, name) VALUES ('wh-r1lrp', 'Wheels / Road / Large / Red / Polish / 5%');
INSERT INTO part (partid, name) VALUES ('fs-r1lrp', 'Front Set / Road / Large / Red / Polish / 5%');
INSERT INTO part (partid, name) VALUES ('pu-r1lrp', 'Pedal Unit / Road / Large / Red / Polish / 5%');
INSERT INTO part (partid, name) VALUES ('sd-r1lrm', 'Saddle / Road / Large / Red / Matte / 5%');
INSERT INTO part (partid, name) VALUES ('fr-r1lrm', 'Frame / Road / Large / Red / Matte / 5%');
INSERT INTO part (partid, name) VALUES ('wh-r1lrm', 'Wheels / Road / Large / Red / Matte / 5%');
INSERT INTO part (partid, name) VALUES ('fs-r1lrm', 'Front Set / Road / Large / Red / Matte / 5%');
INSERT INTO part (partid, name) VALUES ('pu-r1lrm', 'Pedal Unit / Road / Large / Red / Matte / 5%');
INSERT INTO part (partid, name) VALUES ('sd-r2snp', 'Saddle / Road / Small / Black / Polish / 6%');
INSERT INTO part (partid, name) VALUES ('fr-r2snp', 'Frame / Road / Small / Black / Polish / 6%');
INSERT INTO part (partid, name) VALUES ('wh-r2snp', 'Wheels / Road / Small / Black / Polish / 6%');
INSERT INTO part (partid, name) VALUES ('fs-r2snp', 'Front Set / Road / Small / Black / Polish / 6%');
INSERT INTO part (partid, name) VALUES ('pu-r2snp', 'Pedal Unit / Road / Small / Black / Polish / 6%');
INSERT INTO part (partid, name) VALUES ('sd-r2snm', 'Saddle / Road / Small / Black / Matte / 6%');
INSERT INTO part (partid, name) VALUES ('fr-r2snm', 'Frame / Road / Small / Black / Matte / 6%');
INSERT INTO part (partid, name) VALUES ('wh-r2snm', 'Wheels / Road / Small / Black / Matte / 6%');
INSERT INTO part (partid, name) VALUES ('fs-r2snm', 'Front Set / Road / Small / Black / Matte / 6%');
INSERT INTO part (partid, name) VALUES ('pu-r2snm', 'Pedal Unit / Road / Small / Black / Matte / 6%');
INSERT INTO part (partid, name) VALUES ('sd-r2swp', 'Saddle / Road / Small / White / Polish / 6%');
INSERT INTO part (partid, name) VALUES ('fr-r2swp', 'Frame / Road / Small / White / Polish / 6%');
INSERT INTO part (partid, name) VALUES ('wh-r2swp', 'Wheels / Road / Small / White / Polish / 6%');
INSERT INTO part (partid, name) VALUES ('fs-r2swp', 'Front Set / Road / Small / White / Polish / 6%');
INSERT INTO part (partid, name) VALUES ('pu-r2swp', 'Pedal Unit / Road / Small / White / Polish / 6%');
INSERT INTO part (partid, name) VALUES ('sd-r2swm', 'Saddle / Road / Small / White / Matte / 6%');
INSERT INTO part (partid, name) VALUES ('fr-r2swm', 'Frame / Road / Small / White / Matte / 6%');
INSERT INTO part (partid, name) VALUES ('wh-r2swm', 'Wheels / Road / Small / White / Matte / 6%');
INSERT INTO part (partid, name) VALUES ('fs-r2swm', 'Front Set / Road / Small / White / Matte / 6%');
INSERT INTO part (partid, name) VALUES ('pu-r2swm', 'Pedal Unit / Road / Small / White / Matte / 6%');
INSERT INTO part (partid, name) VALUES ('sd-r2sbp', 'Saddle / Road / Small / Blue / Polish / 6%');
INSERT INTO part (partid, name) VALUES ('fr-r2sbp', 'Frame / Road / Small / Blue / Polish / 6%');
INSERT INTO part (partid, name) VALUES ('wh-r2sbp', 'Wheels / Road / Small / Blue / Polish / 6%');
INSERT INTO part (partid, name) VALUES ('fs-r2sbp', 'Front Set / Road / Small / Blue / Polish / 6%');
INSERT INTO part (partid, name) VALUES ('pu-r2sbp', 'Pedal Unit / Road / Small / Blue / Polish / 6%');
INSERT INTO part (partid, name) VALUES ('sd-r2sbm', 'Saddle / Road / Small / Blue / Matte / 6%');
INSERT INTO part (partid, name) VALUES ('fr-r2sbm', 'Frame / Road / Small / Blue / Matte / 6%');
INSERT INTO part (partid, name) VALUES ('wh-r2sbm', 'Wheels / Road / Small / Blue / Matte / 6%');
INSERT INTO part (partid, name) VALUES ('fs-r2sbm', 'Front Set / Road / Small / Blue / Matte / 6%');
INSERT INTO part (partid, name) VALUES ('pu-r2sbm', 'Pedal Unit / Road / Small / Blue / Matte / 6%');
INSERT INTO part (partid, name) VALUES ('sd-r2syp', 'Saddle / Road / Small / Yellow / Polish / 6%');
INSERT INTO part (partid, name) VALUES ('fr-r2syp', 'Frame / Road / Small / Yellow / Polish / 6%');
INSERT INTO part (partid, name) VALUES ('wh-r2syp', 'Wheels / Road / Small / Yellow / Polish / 6%');
INSERT INTO part (partid, name) VALUES ('fs-r2syp', 'Front Set / Road / Small / Yellow / Polish / 6%');
INSERT INTO part (partid, name) VALUES ('pu-r2syp', 'Pedal Unit / Road / Small / Yellow / Polish / 6%');
INSERT INTO part (partid, name) VALUES ('sd-r2sym', 'Saddle / Road / Small / Yellow / Matte / 6%');
INSERT INTO part (partid, name) VALUES ('fr-r2sym', 'Frame / Road / Small / Yellow / Matte / 6%');
INSERT INTO part (partid, name) VALUES ('wh-r2sym', 'Wheels / Road / Small / Yellow / Matte / 6%');
INSERT INTO part (partid, name) VALUES ('fs-r2sym', 'Front Set / Road / Small / Yellow / Matte / 6%');
INSERT INTO part (partid, name) VALUES ('pu-r2sym', 'Pedal Unit / Road / Small / Yellow / Matte / 6%');
INSERT INTO part (partid, name) VALUES ('sd-r2srp', 'Saddle / Road / Small / Red / Polish / 6%');
INSERT INTO part (partid, name) VALUES ('fr-r2srp', 'Frame / Road / Small / Red / Polish / 6%');
INSERT INTO part (partid, name) VALUES ('wh-r2srp', 'Wheels / Road / Small / Red / Polish / 6%');
INSERT INTO part (partid, name) VALUES ('fs-r2srp', 'Front Set / Road / Small / Red / Polish / 6%');
INSERT INTO part (partid, name) VALUES ('pu-r2srp', 'Pedal Unit / Road / Small / Red / Polish / 6%');
INSERT INTO part (partid, name) VALUES ('sd-r2srm', 'Saddle / Road / Small / Red / Matte / 6%');
INSERT INTO part (partid, name) VALUES ('fr-r2srm', 'Frame / Road / Small / Red / Matte / 6%');
INSERT INTO part (partid, name) VALUES ('wh-r2srm', 'Wheels / Road / Small / Red / Matte / 6%');
INSERT INTO part (partid, name) VALUES ('fs-r2srm', 'Front Set / Road / Small / Red / Matte / 6%');
INSERT INTO part (partid, name) VALUES ('pu-r2srm', 'Pedal Unit / Road / Small / Red / Matte / 6%');
INSERT INTO part (partid, name) VALUES ('sd-r2mnp', 'Saddle / Road / Medium / Black / Polish / 6%');
INSERT INTO part (partid, name) VALUES ('fr-r2mnp', 'Frame / Road / Medium / Black / Polish / 6%');
INSERT INTO part (partid, name) VALUES ('wh-r2mnp', 'Wheels / Road / Medium / Black / Polish / 6%');
INSERT INTO part (partid, name) VALUES ('fs-r2mnp', 'Front Set / Road / Medium / Black / Polish / 6%');
INSERT INTO part (partid, name) VALUES ('pu-r2mnp', 'Pedal Unit / Road / Medium / Black / Polish / 6%');
INSERT INTO part (partid, name) VALUES ('sd-r2mnm', 'Saddle / Road / Medium / Black / Matte / 6%');
INSERT INTO part (partid, name) VALUES ('fr-r2mnm', 'Frame / Road / Medium / Black / Matte / 6%');
INSERT INTO part (partid, name) VALUES ('wh-r2mnm', 'Wheels / Road / Medium / Black / Matte / 6%');
INSERT INTO part (partid, name) VALUES ('fs-r2mnm', 'Front Set / Road / Medium / Black / Matte / 6%');
INSERT INTO part (partid, name) VALUES ('pu-r2mnm', 'Pedal Unit / Road / Medium / Black / Matte / 6%');
INSERT INTO part (partid, name) VALUES ('sd-r2mwp', 'Saddle / Road / Medium / White / Polish / 6%');
INSERT INTO part (partid, name) VALUES ('fr-r2mwp', 'Frame / Road / Medium / White / Polish / 6%');
INSERT INTO part (partid, name) VALUES ('wh-r2mwp', 'Wheels / Road / Medium / White / Polish / 6%');
INSERT INTO part (partid, name) VALUES ('fs-r2mwp', 'Front Set / Road / Medium / White / Polish / 6%');
INSERT INTO part (partid, name) VALUES ('pu-r2mwp', 'Pedal Unit / Road / Medium / White / Polish / 6%');
INSERT INTO part (partid, name) VALUES ('sd-r2mwm', 'Saddle / Road / Medium / White / Matte / 6%');
INSERT INTO part (partid, name) VALUES ('fr-r2mwm', 'Frame / Road / Medium / White / Matte / 6%');
INSERT INTO part (partid, name) VALUES ('wh-r2mwm', 'Wheels / Road / Medium / White / Matte / 6%');
INSERT INTO part (partid, name) VALUES ('fs-r2mwm', 'Front Set / Road / Medium / White / Matte / 6%');
INSERT INTO part (partid, name) VALUES ('pu-r2mwm', 'Pedal Unit / Road / Medium / White / Matte / 6%');
INSERT INTO part (partid, name) VALUES ('sd-r2mbp', 'Saddle / Road / Medium / Blue / Polish / 6%');
INSERT INTO part (partid, name) VALUES ('fr-r2mbp', 'Frame / Road / Medium / Blue / Polish / 6%');
INSERT INTO part (partid, name) VALUES ('wh-r2mbp', 'Wheels / Road / Medium / Blue / Polish / 6%');
INSERT INTO part (partid, name) VALUES ('fs-r2mbp', 'Front Set / Road / Medium / Blue / Polish / 6%');
INSERT INTO part (partid, name) VALUES ('pu-r2mbp', 'Pedal Unit / Road / Medium / Blue / Polish / 6%');
INSERT INTO part (partid, name) VALUES ('sd-r2mbm', 'Saddle / Road / Medium / Blue / Matte / 6%');
INSERT INTO part (partid, name) VALUES ('fr-r2mbm', 'Frame / Road / Medium / Blue / Matte / 6%');
INSERT INTO part (partid, name) VALUES ('wh-r2mbm', 'Wheels / Road / Medium / Blue / Matte / 6%');
INSERT INTO part (partid, name) VALUES ('fs-r2mbm', 'Front Set / Road / Medium / Blue / Matte / 6%');
INSERT INTO part (partid, name) VALUES ('pu-r2mbm', 'Pedal Unit / Road / Medium / Blue / Matte / 6%');
INSERT INTO part (partid, name) VALUES ('sd-r2myp', 'Saddle / Road / Medium / Yellow / Polish / 6%');
INSERT INTO part (partid, name) VALUES ('fr-r2myp', 'Frame / Road / Medium / Yellow / Polish / 6%');
INSERT INTO part (partid, name) VALUES ('wh-r2myp', 'Wheels / Road / Medium / Yellow / Polish / 6%');
INSERT INTO part (partid, name) VALUES ('fs-r2myp', 'Front Set / Road / Medium / Yellow / Polish / 6%');
INSERT INTO part (partid, name) VALUES ('pu-r2myp', 'Pedal Unit / Road / Medium / Yellow / Polish / 6%');
INSERT INTO part (partid, name) VALUES ('sd-r2mym', 'Saddle / Road / Medium / Yellow / Matte / 6%');
INSERT INTO part (partid, name) VALUES ('fr-r2mym', 'Frame / Road / Medium / Yellow / Matte / 6%');
INSERT INTO part (partid, name) VALUES ('wh-r2mym', 'Wheels / Road / Medium / Yellow / Matte / 6%');
INSERT INTO part (partid, name) VALUES ('fs-r2mym', 'Front Set / Road / Medium / Yellow / Matte / 6%');
INSERT INTO part (partid, name) VALUES ('pu-r2mym', 'Pedal Unit / Road / Medium / Yellow / Matte / 6%');
INSERT INTO part (partid, name) VALUES ('sd-r2mrp', 'Saddle / Road / Medium / Red / Polish / 6%');
INSERT INTO part (partid, name) VALUES ('fr-r2mrp', 'Frame / Road / Medium / Red / Polish / 6%');
INSERT INTO part (partid, name) VALUES ('wh-r2mrp', 'Wheels / Road / Medium / Red / Polish / 6%');
INSERT INTO part (partid, name) VALUES ('fs-r2mrp', 'Front Set / Road / Medium / Red / Polish / 6%');
INSERT INTO part (partid, name) VALUES ('pu-r2mrp', 'Pedal Unit / Road / Medium / Red / Polish / 6%');
INSERT INTO part (partid, name) VALUES ('sd-r2mrm', 'Saddle / Road / Medium / Red / Matte / 6%');
INSERT INTO part (partid, name) VALUES ('fr-r2mrm', 'Frame / Road / Medium / Red / Matte / 6%');
INSERT INTO part (partid, name) VALUES ('wh-r2mrm', 'Wheels / Road / Medium / Red / Matte / 6%');
INSERT INTO part (partid, name) VALUES ('fs-r2mrm', 'Front Set / Road / Medium / Red / Matte / 6%');
INSERT INTO part (partid, name) VALUES ('pu-r2mrm', 'Pedal Unit / Road / Medium / Red / Matte / 6%');
INSERT INTO part (partid, name) VALUES ('sd-r2lnp', 'Saddle / Road / Large / Black / Polish / 6%');
INSERT INTO part (partid, name) VALUES ('fr-r2lnp', 'Frame / Road / Large / Black / Polish / 6%');
INSERT INTO part (partid, name) VALUES ('wh-r2lnp', 'Wheels / Road / Large / Black / Polish / 6%');
INSERT INTO part (partid, name) VALUES ('fs-r2lnp', 'Front Set / Road / Large / Black / Polish / 6%');
INSERT INTO part (partid, name) VALUES ('pu-r2lnp', 'Pedal Unit / Road / Large / Black / Polish / 6%');
INSERT INTO part (partid, name) VALUES ('sd-r2lnm', 'Saddle / Road / Large / Black / Matte / 6%');
INSERT INTO part (partid, name) VALUES ('fr-r2lnm', 'Frame / Road / Large / Black / Matte / 6%');
INSERT INTO part (partid, name) VALUES ('wh-r2lnm', 'Wheels / Road / Large / Black / Matte / 6%');
INSERT INTO part (partid, name) VALUES ('fs-r2lnm', 'Front Set / Road / Large / Black / Matte / 6%');
INSERT INTO part (partid, name) VALUES ('pu-r2lnm', 'Pedal Unit / Road / Large / Black / Matte / 6%');
INSERT INTO part (partid, name) VALUES ('sd-r2lwp', 'Saddle / Road / Large / White / Polish / 6%');
INSERT INTO part (partid, name) VALUES ('fr-r2lwp', 'Frame / Road / Large / White / Polish / 6%');
INSERT INTO part (partid, name) VALUES ('wh-r2lwp', 'Wheels / Road / Large / White / Polish / 6%');
INSERT INTO part (partid, name) VALUES ('fs-r2lwp', 'Front Set / Road / Large / White / Polish / 6%');
INSERT INTO part (partid, name) VALUES ('pu-r2lwp', 'Pedal Unit / Road / Large / White / Polish / 6%');
INSERT INTO part (partid, name) VALUES ('sd-r2lwm', 'Saddle / Road / Large / White / Matte / 6%');
INSERT INTO part (partid, name) VALUES ('fr-r2lwm', 'Frame / Road / Large / White / Matte / 6%');
INSERT INTO part (partid, name) VALUES ('wh-r2lwm', 'Wheels / Road / Large / White / Matte / 6%');
INSERT INTO part (partid, name) VALUES ('fs-r2lwm', 'Front Set / Road / Large / White / Matte / 6%');
INSERT INTO part (partid, name) VALUES ('pu-r2lwm', 'Pedal Unit / Road / Large / White / Matte / 6%');
INSERT INTO part (partid, name) VALUES ('sd-r2lbp', 'Saddle / Road / Large / Blue / Polish / 6%');
INSERT INTO part (partid, name) VALUES ('fr-r2lbp', 'Frame / Road / Large / Blue / Polish / 6%');
INSERT INTO part (partid, name) VALUES ('wh-r2lbp', 'Wheels / Road / Large / Blue / Polish / 6%');
INSERT INTO part (partid, name) VALUES ('fs-r2lbp', 'Front Set / Road / Large / Blue / Polish / 6%');
INSERT INTO part (partid, name) VALUES ('pu-r2lbp', 'Pedal Unit / Road / Large / Blue / Polish / 6%');
INSERT INTO part (partid, name) VALUES ('sd-r2lbm', 'Saddle / Road / Large / Blue / Matte / 6%');
INSERT INTO part (partid, name) VALUES ('fr-r2lbm', 'Frame / Road / Large / Blue / Matte / 6%');
INSERT INTO part (partid, name) VALUES ('wh-r2lbm', 'Wheels / Road / Large / Blue / Matte / 6%');
INSERT INTO part (partid, name) VALUES ('fs-r2lbm', 'Front Set / Road / Large / Blue / Matte / 6%');
INSERT INTO part (partid, name) VALUES ('pu-r2lbm', 'Pedal Unit / Road / Large / Blue / Matte / 6%');
INSERT INTO part (partid, name) VALUES ('sd-r2lyp', 'Saddle / Road / Large / Yellow / Polish / 6%');
INSERT INTO part (partid, name) VALUES ('fr-r2lyp', 'Frame / Road / Large / Yellow / Polish / 6%');
INSERT INTO part (partid, name) VALUES ('wh-r2lyp', 'Wheels / Road / Large / Yellow / Polish / 6%');
INSERT INTO part (partid, name) VALUES ('fs-r2lyp', 'Front Set / Road / Large / Yellow / Polish / 6%');
INSERT INTO part (partid, name) VALUES ('pu-r2lyp', 'Pedal Unit / Road / Large / Yellow / Polish / 6%');
INSERT INTO part (partid, name) VALUES ('sd-r2lym', 'Saddle / Road / Large / Yellow / Matte / 6%');
INSERT INTO part (partid, name) VALUES ('fr-r2lym', 'Frame / Road / Large / Yellow / Matte / 6%');
INSERT INTO part (partid, name) VALUES ('wh-r2lym', 'Wheels / Road / Large / Yellow / Matte / 6%');
INSERT INTO part (partid, name) VALUES ('fs-r2lym', 'Front Set / Road / Large / Yellow / Matte / 6%');
INSERT INTO part (partid, name) VALUES ('pu-r2lym', 'Pedal Unit / Road / Large / Yellow / Matte / 6%');
INSERT INTO part (partid, name) VALUES ('sd-r2lrp', 'Saddle / Road / Large / Red / Polish / 6%');
INSERT INTO part (partid, name) VALUES ('fr-r2lrp', 'Frame / Road / Large / Red / Polish / 6%');
INSERT INTO part (partid, name) VALUES ('wh-r2lrp', 'Wheels / Road / Large / Red / Polish / 6%');
INSERT INTO part (partid, name) VALUES ('fs-r2lrp', 'Front Set / Road / Large / Red / Polish / 6%');
INSERT INTO part (partid, name) VALUES ('pu-r2lrp', 'Pedal Unit / Road / Large / Red / Polish / 6%');
INSERT INTO part (partid, name) VALUES ('sd-r2lrm', 'Saddle / Road / Large / Red / Matte / 6%');
INSERT INTO part (partid, name) VALUES ('fr-r2lrm', 'Frame / Road / Large / Red / Matte / 6%');
INSERT INTO part (partid, name) VALUES ('wh-r2lrm', 'Wheels / Road / Large / Red / Matte / 6%');
INSERT INTO part (partid, name) VALUES ('fs-r2lrm', 'Front Set / Road / Large / Red / Matte / 6%');
INSERT INTO part (partid, name) VALUES ('pu-r2lrm', 'Pedal Unit / Road / Large / Red / Matte / 6%');