-- This is instances for material table
INSERT INTO material (materialid, name) VALUES ('dt-m1snp', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-m1snm', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-m1swp', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-m1swm', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-m1sbp', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-m1sbm', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-m1syp', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-m1sym', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-m1srp', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-m1srm', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-m1mnp', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-m1mnm', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-m1mwp', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-m1mwm', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-m1mbp', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-m1mbm', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-m1myp', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-m1mym', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-m1mrp', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-m1mrm', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-m1lnp', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-m1lnm', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-m1lwp', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-m1lwm', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-m1lbp', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-m1lbm', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-m1lyp', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-m1lym', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-m1lrp', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-m1lrm', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-m2snp', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-m2snm', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-m2swp', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-m2swm', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-m2sbp', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-m2sbm', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-m2syp', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-m2sym', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-m2srp', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-m2srm', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-m2mnp', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-m2mnm', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-m2mwp', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-m2mwm', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-m2mbp', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-m2mbm', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-m2myp', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-m2mym', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-m2mrp', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-m2mrm', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-m2lnp', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-m2lnm', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-m2lwp', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-m2lwm', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-m2lbp', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-m2lbm', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-m2lyp', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-m2lym', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-m2lrp', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-m2lrm', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-r1snp', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-r1snm', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-r1swp', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-r1swm', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-r1sbp', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-r1sbm', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-r1syp', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-r1sym', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-r1srp', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-r1srm', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-r1mnp', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-r1mnm', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-r1mwp', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-r1mwm', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-r1mbp', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-r1mbm', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-r1myp', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-r1mym', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-r1mrp', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-r1mrm', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-r1lnp', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-r1lnm', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-r1lwp', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-r1lwm', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-r1lbp', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-r1lbm', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-r1lyp', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-r1lym', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-r1lrp', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-r1lrm', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-r2snp', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-r2snm', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-r2swp', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-r2swm', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-r2sbp', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-r2sbm', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-r2syp', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-r2sym', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-r2srp', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-r2srm', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-r2mnp', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-r2mnm', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-r2mwp', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-r2mwm', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-r2mbp', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-r2mbm', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-r2myp', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-r2mym', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-r2mrp', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-r2mrm', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-r2lnp', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-r2lnm', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-r2lwp', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-r2lwm', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-r2lbp', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-r2lbm', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-r2lyp', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-r2lym', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-r2lrp', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('dt-r2lrm', 'Down Tube');
INSERT INTO material (materialid, name) VALUES ('st-m1snp', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-m1snm', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-m1swp', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-m1swm', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-m1sbp', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-m1sbm', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-m1syp', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-m1sym', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-m1srp', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-m1srm', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-m1mnp', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-m1mnm', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-m1mwp', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-m1mwm', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-m1mbp', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-m1mbm', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-m1myp', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-m1mym', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-m1mrp', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-m1mrm', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-m1lnp', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-m1lnm', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-m1lwp', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-m1lwm', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-m1lbp', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-m1lbm', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-m1lyp', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-m1lym', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-m1lrp', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-m1lrm', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-m2snp', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-m2snm', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-m2swp', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-m2swm', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-m2sbp', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-m2sbm', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-m2syp', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-m2sym', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-m2srp', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-m2srm', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-m2mnp', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-m2mnm', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-m2mwp', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-m2mwm', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-m2mbp', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-m2mbm', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-m2myp', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-m2mym', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-m2mrp', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-m2mrm', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-m2lnp', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-m2lnm', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-m2lwp', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-m2lwm', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-m2lbp', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-m2lbm', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-m2lyp', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-m2lym', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-m2lrp', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-m2lrm', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-r1snp', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-r1snm', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-r1swp', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-r1swm', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-r1sbp', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-r1sbm', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-r1syp', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-r1sym', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-r1srp', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-r1srm', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-r1mnp', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-r1mnm', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-r1mwp', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-r1mwm', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-r1mbp', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-r1mbm', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-r1myp', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-r1mym', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-r1mrp', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-r1mrm', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-r1lnp', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-r1lnm', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-r1lwp', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-r1lwm', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-r1lbp', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-r1lbm', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-r1lyp', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-r1lym', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-r1lrp', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-r1lrm', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-r2snp', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-r2snm', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-r2swp', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-r2swm', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-r2sbp', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-r2sbm', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-r2syp', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-r2sym', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-r2srp', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-r2srm', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-r2mnp', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-r2mnm', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-r2mwp', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-r2mwm', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-r2mbp', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-r2mbm', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-r2myp', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-r2mym', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-r2mrp', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-r2mrm', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-r2lnp', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-r2lnm', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-r2lwp', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-r2lwm', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-r2lbp', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-r2lbm', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-r2lyp', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-r2lym', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-r2lrp', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('st-r2lrm', 'Seat Tube');
INSERT INTO material (materialid, name) VALUES ('se-m1snp', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-m1snm', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-m1swp', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-m1swm', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-m1sbp', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-m1sbm', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-m1syp', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-m1sym', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-m1srp', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-m1srm', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-m1mnp', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-m1mnm', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-m1mwp', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-m1mwm', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-m1mbp', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-m1mbm', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-m1myp', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-m1mym', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-m1mrp', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-m1mrm', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-m1lnp', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-m1lnm', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-m1lwp', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-m1lwm', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-m1lbp', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-m1lbm', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-m1lyp', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-m1lym', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-m1lrp', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-m1lrm', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-m2snp', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-m2snm', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-m2swp', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-m2swm', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-m2sbp', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-m2sbm', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-m2syp', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-m2sym', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-m2srp', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-m2srm', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-m2mnp', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-m2mnm', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-m2mwp', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-m2mwm', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-m2mbp', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-m2mbm', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-m2myp', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-m2mym', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-m2mrp', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-m2mrm', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-m2lnp', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-m2lnm', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-m2lwp', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-m2lwm', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-m2lbp', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-m2lbm', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-m2lyp', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-m2lym', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-m2lrp', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-m2lrm', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-r1snp', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-r1snm', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-r1swp', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-r1swm', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-r1sbp', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-r1sbm', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-r1syp', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-r1sym', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-r1srp', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-r1srm', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-r1mnp', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-r1mnm', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-r1mwp', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-r1mwm', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-r1mbp', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-r1mbm', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-r1myp', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-r1mym', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-r1mrp', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-r1mrm', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-r1lnp', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-r1lnm', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-r1lwp', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-r1lwm', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-r1lbp', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-r1lbm', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-r1lyp', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-r1lym', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-r1lrp', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-r1lrm', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-r2snp', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-r2snm', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-r2swp', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-r2swm', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-r2sbp', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-r2sbm', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-r2syp', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-r2sym', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-r2srp', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-r2srm', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-r2mnp', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-r2mnm', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-r2mwp', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-r2mwm', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-r2mbp', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-r2mbm', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-r2myp', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-r2mym', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-r2mrp', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-r2mrm', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-r2lnp', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-r2lnm', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-r2lwp', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-r2lwm', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-r2lbp', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-r2lbm', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-r2lyp', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-r2lym', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-r2lrp', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('se-r2lrm', 'Seat Stay');
INSERT INTO material (materialid, name) VALUES ('cs-m1snp', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-m1snm', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-m1swp', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-m1swm', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-m1sbp', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-m1sbm', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-m1syp', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-m1sym', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-m1srp', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-m1srm', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-m1mnp', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-m1mnm', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-m1mwp', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-m1mwm', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-m1mbp', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-m1mbm', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-m1myp', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-m1mym', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-m1mrp', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-m1mrm', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-m1lnp', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-m1lnm', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-m1lwp', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-m1lwm', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-m1lbp', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-m1lbm', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-m1lyp', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-m1lym', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-m1lrp', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-m1lrm', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-m2snp', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-m2snm', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-m2swp', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-m2swm', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-m2sbp', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-m2sbm', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-m2syp', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-m2sym', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-m2srp', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-m2srm', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-m2mnp', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-m2mnm', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-m2mwp', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-m2mwm', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-m2mbp', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-m2mbm', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-m2myp', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-m2mym', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-m2mrp', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-m2mrm', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-m2lnp', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-m2lnm', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-m2lwp', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-m2lwm', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-m2lbp', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-m2lbm', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-m2lyp', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-m2lym', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-m2lrp', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-m2lrm', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-r1snp', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-r1snm', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-r1swp', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-r1swm', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-r1sbp', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-r1sbm', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-r1syp', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-r1sym', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-r1srp', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-r1srm', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-r1mnp', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-r1mnm', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-r1mwp', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-r1mwm', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-r1mbp', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-r1mbm', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-r1myp', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-r1mym', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-r1mrp', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-r1mrm', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-r1lnp', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-r1lnm', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-r1lwp', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-r1lwm', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-r1lbp', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-r1lbm', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-r1lyp', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-r1lym', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-r1lrp', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-r1lrm', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-r2snp', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-r2snm', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-r2swp', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-r2swm', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-r2sbp', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-r2sbm', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-r2syp', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-r2sym', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-r2srp', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-r2srm', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-r2mnp', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-r2mnm', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-r2mwp', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-r2mwm', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-r2mbp', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-r2mbm', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-r2myp', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-r2mym', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-r2mrp', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-r2mrm', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-r2lnp', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-r2lnm', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-r2lwp', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-r2lwm', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-r2lbp', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-r2lbm', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-r2lyp', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-r2lym', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-r2lrp', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('cs-r2lrm', 'Chain Stay');
INSERT INTO material (materialid, name) VALUES ('tt-m1snp', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-m1snm', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-m1swp', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-m1swm', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-m1sbp', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-m1sbm', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-m1syp', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-m1sym', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-m1srp', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-m1srm', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-m1mnp', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-m1mnm', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-m1mwp', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-m1mwm', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-m1mbp', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-m1mbm', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-m1myp', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-m1mym', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-m1mrp', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-m1mrm', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-m1lnp', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-m1lnm', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-m1lwp', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-m1lwm', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-m1lbp', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-m1lbm', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-m1lyp', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-m1lym', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-m1lrp', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-m1lrm', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-m2snp', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-m2snm', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-m2swp', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-m2swm', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-m2sbp', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-m2sbm', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-m2syp', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-m2sym', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-m2srp', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-m2srm', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-m2mnp', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-m2mnm', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-m2mwp', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-m2mwm', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-m2mbp', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-m2mbm', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-m2myp', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-m2mym', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-m2mrp', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-m2mrm', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-m2lnp', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-m2lnm', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-m2lwp', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-m2lwm', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-m2lbp', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-m2lbm', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-m2lyp', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-m2lym', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-m2lrp', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-m2lrm', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-r1snp', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-r1snm', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-r1swp', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-r1swm', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-r1sbp', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-r1sbm', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-r1syp', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-r1sym', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-r1srp', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-r1srm', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-r1mnp', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-r1mnm', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-r1mwp', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-r1mwm', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-r1mbp', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-r1mbm', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-r1myp', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-r1mym', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-r1mrp', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-r1mrm', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-r1lnp', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-r1lnm', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-r1lwp', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-r1lwm', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-r1lbp', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-r1lbm', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-r1lyp', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-r1lym', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-r1lrp', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-r1lrm', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-r2snp', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-r2snm', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-r2swp', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-r2swm', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-r2sbp', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-r2sbm', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-r2syp', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-r2sym', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-r2srp', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-r2srm', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-r2mnp', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-r2mnm', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-r2mwp', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-r2mwm', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-r2mbp', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-r2mbm', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-r2myp', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-r2mym', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-r2mrp', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-r2mrm', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-r2lnp', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-r2lnm', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-r2lwp', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-r2lwm', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-r2lbp', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-r2lbm', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-r2lyp', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-r2lym', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-r2lrp', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('tt-r2lrm', 'Top Tube');
INSERT INTO material (materialid, name) VALUES ('ht-m1snp', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-m1snm', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-m1swp', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-m1swm', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-m1sbp', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-m1sbm', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-m1syp', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-m1sym', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-m1srp', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-m1srm', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-m1mnp', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-m1mnm', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-m1mwp', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-m1mwm', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-m1mbp', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-m1mbm', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-m1myp', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-m1mym', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-m1mrp', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-m1mrm', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-m1lnp', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-m1lnm', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-m1lwp', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-m1lwm', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-m1lbp', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-m1lbm', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-m1lyp', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-m1lym', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-m1lrp', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-m1lrm', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-m2snp', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-m2snm', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-m2swp', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-m2swm', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-m2sbp', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-m2sbm', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-m2syp', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-m2sym', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-m2srp', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-m2srm', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-m2mnp', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-m2mnm', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-m2mwp', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-m2mwm', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-m2mbp', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-m2mbm', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-m2myp', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-m2mym', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-m2mrp', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-m2mrm', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-m2lnp', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-m2lnm', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-m2lwp', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-m2lwm', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-m2lbp', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-m2lbm', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-m2lyp', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-m2lym', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-m2lrp', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-m2lrm', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-r1snp', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-r1snm', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-r1swp', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-r1swm', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-r1sbp', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-r1sbm', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-r1syp', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-r1sym', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-r1srp', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-r1srm', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-r1mnp', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-r1mnm', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-r1mwp', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-r1mwm', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-r1mbp', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-r1mbm', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-r1myp', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-r1mym', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-r1mrp', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-r1mrm', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-r1lnp', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-r1lnm', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-r1lwp', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-r1lwm', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-r1lbp', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-r1lbm', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-r1lyp', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-r1lym', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-r1lrp', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-r1lrm', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-r2snp', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-r2snm', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-r2swp', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-r2swm', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-r2sbp', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-r2sbm', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-r2syp', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-r2sym', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-r2srp', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-r2srm', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-r2mnp', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-r2mnm', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-r2mwp', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-r2mwm', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-r2mbp', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-r2mbm', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-r2myp', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-r2mym', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-r2mrp', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-r2mrm', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-r2lnp', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-r2lnm', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-r2lwp', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-r2lwm', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-r2lbp', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-r2lbm', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-r2lyp', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-r2lym', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-r2lrp', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('ht-r2lrm', 'Head Tube');
INSERT INTO material (materialid, name) VALUES ('fo-m1snp', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-m1snm', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-m1swp', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-m1swm', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-m1sbp', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-m1sbm', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-m1syp', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-m1sym', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-m1srp', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-m1srm', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-m1mnp', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-m1mnm', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-m1mwp', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-m1mwm', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-m1mbp', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-m1mbm', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-m1myp', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-m1mym', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-m1mrp', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-m1mrm', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-m1lnp', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-m1lnm', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-m1lwp', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-m1lwm', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-m1lbp', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-m1lbm', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-m1lyp', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-m1lym', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-m1lrp', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-m1lrm', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-m2snp', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-m2snm', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-m2swp', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-m2swm', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-m2sbp', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-m2sbm', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-m2syp', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-m2sym', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-m2srp', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-m2srm', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-m2mnp', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-m2mnm', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-m2mwp', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-m2mwm', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-m2mbp', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-m2mbm', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-m2myp', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-m2mym', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-m2mrp', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-m2mrm', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-m2lnp', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-m2lnm', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-m2lwp', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-m2lwm', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-m2lbp', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-m2lbm', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-m2lyp', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-m2lym', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-m2lrp', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-m2lrm', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-r1snp', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-r1snm', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-r1swp', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-r1swm', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-r1sbp', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-r1sbm', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-r1syp', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-r1sym', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-r1srp', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-r1srm', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-r1mnp', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-r1mnm', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-r1mwp', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-r1mwm', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-r1mbp', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-r1mbm', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-r1myp', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-r1mym', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-r1mrp', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-r1mrm', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-r1lnp', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-r1lnm', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-r1lwp', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-r1lwm', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-r1lbp', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-r1lbm', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-r1lyp', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-r1lym', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-r1lrp', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-r1lrm', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-r2snp', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-r2snm', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-r2swp', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-r2swm', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-r2sbp', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-r2sbm', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-r2syp', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-r2sym', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-r2srp', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-r2srm', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-r2mnp', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-r2mnm', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-r2mwp', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-r2mwm', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-r2mbp', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-r2mbm', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-r2myp', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-r2mym', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-r2mrp', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-r2mrm', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-r2lnp', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-r2lnm', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-r2lwp', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-r2lwm', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-r2lbp', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-r2lbm', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-r2lyp', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-r2lym', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-r2lrp', 'Fork');
INSERT INTO material (materialid, name) VALUES ('fo-r2lrm', 'Fork');

-- This is instances for material table
INSERT INTO material (materialid, name) VALUES ('sp-m1xxx', 'Seat Post');
INSERT INTO material (materialid, name) VALUES ('sp-m2xxx', 'Seat Post');
INSERT INTO material (materialid, name) VALUES ('sp-r1xxx', 'Seat Post');
INSERT INTO material (materialid, name) VALUES ('sp-r2xxx', 'Seat Post');
INSERT INTO material (materialid, name) VALUES ('ss-m1xxx', 'Saddle Seat');
INSERT INTO material (materialid, name) VALUES ('ss-m2xxx', 'Saddle Seat');
INSERT INTO material (materialid, name) VALUES ('ss-r1xxx', 'Saddle Seat');
INSERT INTO material (materialid, name) VALUES ('ss-r2xxx', 'Saddle Seat');
INSERT INTO material (materialid, name) VALUES ('bo-m1xxx', 'Bone');
INSERT INTO material (materialid, name) VALUES ('bo-m2xxx', 'Bone');
INSERT INTO material (materialid, name) VALUES ('bo-r1xxx', 'Bone');
INSERT INTO material (materialid, name) VALUES ('bo-r2xxx', 'Bone');
INSERT INTO material (materialid, name) VALUES ('rb-m1xxx', 'Rear Brakes');
INSERT INTO material (materialid, name) VALUES ('rb-m2xxx', 'Rear Brakes');
INSERT INTO material (materialid, name) VALUES ('rb-r1xxx', 'Rear Brakes');
INSERT INTO material (materialid, name) VALUES ('rb-r2xxx', 'Rear Brakes');
INSERT INTO material (materialid, name) VALUES ('de-m1xxx', 'Derailleur');
INSERT INTO material (materialid, name) VALUES ('de-m2xxx', 'Derailleur');
INSERT INTO material (materialid, name) VALUES ('de-r1xxx', 'Derailleur');
INSERT INTO material (materialid, name) VALUES ('de-r2xxx', 'Derailleur');
INSERT INTO material (materialid, name) VALUES ('cr-m1xxx', 'Chain Rings');
INSERT INTO material (materialid, name) VALUES ('cr-m2xxx', 'Chain Rings');
INSERT INTO material (materialid, name) VALUES ('cr-r1xxx', 'Chain Rings');
INSERT INTO material (materialid, name) VALUES ('cr-r2xxx', 'Chain Rings');
INSERT INTO material (materialid, name) VALUES ('hu-m1xxx', 'Hub');
INSERT INTO material (materialid, name) VALUES ('hu-m2xxx', 'Hub');
INSERT INTO material (materialid, name) VALUES ('hu-r1xxx', 'Hub');
INSERT INTO material (materialid, name) VALUES ('hu-r2xxx', 'Hub');
INSERT INTO material (materialid, name) VALUES ('hg-m1xxx', 'Handler Grip');
INSERT INTO material (materialid, name) VALUES ('hg-m2xxx', 'Handler Grip');
INSERT INTO material (materialid, name) VALUES ('hg-r1xxx', 'Handler Grip');
INSERT INTO material (materialid, name) VALUES ('hg-r2xxx', 'Handler Grip');
INSERT INTO material (materialid, name) VALUES ('sa-m1xxx', 'Shock Absorber');
INSERT INTO material (materialid, name) VALUES ('sa-m2xxx', 'Shock Absorber');
INSERT INTO material (materialid, name) VALUES ('sa-r1xxx', 'Shock Absorber');
INSERT INTO material (materialid, name) VALUES ('sa-r2xxx', 'Shock Absorber');
INSERT INTO material (materialid, name) VALUES ('fb-m1xxx', 'Front Brakes');
INSERT INTO material (materialid, name) VALUES ('fb-m2xxx', 'Front Brakes');
INSERT INTO material (materialid, name) VALUES ('fb-r1xxx', 'Front Brakes');
INSERT INTO material (materialid, name) VALUES ('fb-r2xxx', 'Front Brakes');

-- This is instances for material table
INSERT INTO material (materialid, name) VALUES ('ch-m1sxx', 'Chain');
INSERT INTO material (materialid, name) VALUES ('ch-m1mxx', 'Chain');
INSERT INTO material (materialid, name) VALUES ('ch-m1lxx', 'Chain');
INSERT INTO material (materialid, name) VALUES ('ch-m2sxx', 'Chain');
INSERT INTO material (materialid, name) VALUES ('ch-m2mxx', 'Chain');
INSERT INTO material (materialid, name) VALUES ('ch-m2lxx', 'Chain');
INSERT INTO material (materialid, name) VALUES ('ch-r1sxx', 'Chain');
INSERT INTO material (materialid, name) VALUES ('ch-r1mxx', 'Chain');
INSERT INTO material (materialid, name) VALUES ('ch-r1lxx', 'Chain');
INSERT INTO material (materialid, name) VALUES ('ch-r2sxx', 'Chain');
INSERT INTO material (materialid, name) VALUES ('ch-r2mxx', 'Chain');
INSERT INTO material (materialid, name) VALUES ('ch-r2lxx', 'Chain');
INSERT INTO material (materialid, name) VALUES ('ri-m1sxx', 'Rim');
INSERT INTO material (materialid, name) VALUES ('ri-m1mxx', 'Rim');
INSERT INTO material (materialid, name) VALUES ('ri-m1lxx', 'Rim');
INSERT INTO material (materialid, name) VALUES ('ri-m2sxx', 'Rim');
INSERT INTO material (materialid, name) VALUES ('ri-m2mxx', 'Rim');
INSERT INTO material (materialid, name) VALUES ('ri-m2lxx', 'Rim');
INSERT INTO material (materialid, name) VALUES ('ri-r1sxx', 'Rim');
INSERT INTO material (materialid, name) VALUES ('ri-r1mxx', 'Rim');
INSERT INTO material (materialid, name) VALUES ('ri-r1lxx', 'Rim');
INSERT INTO material (materialid, name) VALUES ('ri-r2sxx', 'Rim');
INSERT INTO material (materialid, name) VALUES ('ri-r2mxx', 'Rim');
INSERT INTO material (materialid, name) VALUES ('ri-r2lxx', 'Rim');
INSERT INTO material (materialid, name) VALUES ('sk-m1sxx', 'Spokes');
INSERT INTO material (materialid, name) VALUES ('sk-m1mxx', 'Spokes');
INSERT INTO material (materialid, name) VALUES ('sk-m1lxx', 'Spokes');
INSERT INTO material (materialid, name) VALUES ('sk-m2sxx', 'Spokes');
INSERT INTO material (materialid, name) VALUES ('sk-m2mxx', 'Spokes');
INSERT INTO material (materialid, name) VALUES ('sk-m2lxx', 'Spokes');
INSERT INTO material (materialid, name) VALUES ('sk-r1sxx', 'Spokes');
INSERT INTO material (materialid, name) VALUES ('sk-r1mxx', 'Spokes');
INSERT INTO material (materialid, name) VALUES ('sk-r1lxx', 'Spokes');
INSERT INTO material (materialid, name) VALUES ('sk-r2sxx', 'Spokes');
INSERT INTO material (materialid, name) VALUES ('sk-r2mxx', 'Spokes');
INSERT INTO material (materialid, name) VALUES ('sk-r2lxx', 'Spokes');
INSERT INTO material (materialid, name) VALUES ('ti-m1sxx', 'Tire');
INSERT INTO material (materialid, name) VALUES ('ti-m1mxx', 'Tire');
INSERT INTO material (materialid, name) VALUES ('ti-m1lxx', 'Tire');
INSERT INTO material (materialid, name) VALUES ('ti-m2sxx', 'Tire');
INSERT INTO material (materialid, name) VALUES ('ti-m2mxx', 'Tire');
INSERT INTO material (materialid, name) VALUES ('ti-m2lxx', 'Tire');
INSERT INTO material (materialid, name) VALUES ('ti-r1sxx', 'Tire');
INSERT INTO material (materialid, name) VALUES ('ti-r1mxx', 'Tire');
INSERT INTO material (materialid, name) VALUES ('ti-r1lxx', 'Tire');
INSERT INTO material (materialid, name) VALUES ('ti-r2sxx', 'Tire');
INSERT INTO material (materialid, name) VALUES ('ti-r2mxx', 'Tire');
INSERT INTO material (materialid, name) VALUES ('ti-r2lxx', 'Tire');

-- This is instances for material table (NO options)
INSERT INTO material (materialid, name) VALUES ('va-xxxxx', 'Valve');
INSERT INTO material (materialid, name) VALUES ('pe-xxxxx', 'Pedal');
INSERT INTO material (materialid, name) VALUES ('ca-xxxxx', 'Crank Arm');