INSERT INTO rawmaterial (rawmaterialid, name,description, cost,unit) VALUES('alloy', 'Alloy','Alloy', 0.05 , 'Kg');
INSERT INTO rawmaterial (rawmaterialid, name, description, cost,unit) VALUES('steel', 'Steel','Steel', 0.05,'Kg');
INSERT INTO rawmaterial (rawmaterialid, name, description, cost,unit) VALUES('paint', 'Paint','Paint', 0.3,'L');
INSERT INTO rawmaterial (rawmaterialid, name, description, cost,unit) VALUES('rubber', 'Rubber', 'Rubber',0.1,'Kg');
INSERT INTO rawmaterial (rawmaterialid, name, description, cost,unit) VALUES('nylon', 'Nylon Mesh','Nylon Mesh', 2.5,'Kg');
INSERT INTO rawmaterial (rawmaterialid, name, description, cost,unit) VALUES('brake1', 'Long Brake','Long Brake', 5.0,'Piece');
INSERT INTO rawmaterial (rawmaterialid, name, description, cost,unit) VALUES('brake2', 'Short Brake','Short Brake', 4.0,'Piece');
INSERT INTO rawmaterial (rawmaterialid, name, description, cost,unit) VALUES('derailleur1', '3*6 Derailleur','3*6 Derailleur', 20.0 ,'Piece');
INSERT INTO rawmaterial (rawmaterialid, name, description, cost,unit) VALUES('derailleur2', '2*4 Derailleur','2*4 Derailleur', 15.0,'Piece');
INSERT INTO rawmaterial (rawmaterialid, name, description, cost,unit) VALUES('hub1', 'Mountain Bike Hub','Mountain Bike Hub', 3.0,'Piece');
INSERT INTO rawmaterial (rawmaterialid, name, description, cost,unit) VALUES('hub2', 'Road Bike Hub','Road Bike Hub', 2.5,'Piece');
INSERT INTO rawmaterial (rawmaterialid, name, description, cost,unit) VALUES('shockAbs1', 'Mountain Bike Shock Absorber','Mountain Bike Shock Absorber', 10.0,'Piece');
INSERT INTO rawmaterial (rawmaterialid, name, description, cost,unit) VALUES('shockAbs2', 'Road Bike Shock Absorber','Road Bike Shock Absorber', 8.0,'Piece');
INSERT INTO rawmaterial (rawmaterialid, name, description, cost,unit) VALUES('valve', 'Valve', 'Valve', 4.0,'Piece');
INSERT INTO rawmaterial (rawmaterialid, name, description, cost,unit) VALUES('pedal', 'Pedal','Pedal', 3.0,'Piece');
INSERT INTO rawmaterial (rawmaterialid, name, description, cost,unit) VALUES('crankarm', 'Crank Arm','Crank Arm', 2.5,'Piece');